// ═══ Shader DSL — build-time example data (shared by index + detail pages) ═══
//
// Emits WGSL / GLSL ES 3.00 / reflection from the SAME example modules the CLI and the
// e2e render-gate use, and reads each example's raw source for display — all at BUILD time.
// The /shader-dsl index (gallery) and the /shader-dsl/[id] detail pages both consume this,
// so the emit happens once and neither page bundles @xgis/shader-dsl into the client.
import { examples, type Control } from '../../../shader-dsl/examples/index.ts'
import { emitModule, emitGlslModule, reflect } from '../../../shader-dsl/src/index.ts'

const rawSources = import.meta.glob('../../../shader-dsl/examples/*.ts', {
  query: '?raw', import: 'default', eager: true,
}) as Record<string, string>
const sourceByFile = Object.fromEntries(
  Object.entries(rawSources).map(([p, src]) => [p.split('/').pop()!, src]),
)

/** Compact render spec for the client WebGL2 runner (renderable examples only). */
export interface RenderSpec {
  id: string
  vertex: string
  fragment: string
  reflection: ReturnType<typeof reflect>
  controls: Record<string, Control>
}

export interface ShaderCard {
  id: string
  title: string
  blurb: string
  category: 'cartographic' | 'generic' | 'compute'
  /** Source-file basename (with .ts) — for the "view source on GitHub" link. */
  file: string
  renderable: boolean
  /** Static gallery thumbnail (generated by playground/capture-shader-thumbnails.mts). */
  thumb: string | null
  source: string
  wgsl: string
  glsl: string | null
  /** Pretty-printed reflection JSON for the "Reflection" tab. */
  reflectionJson: string
  /** Live-render spec for the client (renderable only). */
  spec: RenderSpec | null
}

const base = import.meta.env.BASE_URL.replace(/\/+$/, '')

export const shaderCards: ShaderCard[] = examples.map((ex) => {
  const renderable = ex.renderable
  const glsl = renderable
    ? `// ─────────── vertex ───────────\n${emitGlslModule(ex.module, 'vertex')}\n\n// ────────── fragment ──────────\n${emitGlslModule(ex.module, 'fragment')}`
    : null
  return {
    id: ex.id,
    title: ex.title,
    blurb: ex.blurb,
    category: ex.category,
    file: ex.file,
    renderable,
    thumb: renderable ? `${base}/shader/${ex.id}.jpg` : null,
    source: sourceByFile[ex.file] ?? '',
    wgsl: emitModule(ex.module),
    glsl,
    reflectionJson: JSON.stringify(reflect(ex.module), null, 2),
    spec: renderable
      ? {
          id: ex.id,
          vertex: emitGlslModule(ex.module, 'vertex'),
          fragment: emitGlslModule(ex.module, 'fragment'),
          reflection: reflect(ex.module),
          controls: ex.controls ?? {},
        }
      : null,
  }
})

export const categoryGroups = [
  {
    key: 'cartographic' as const,
    title: 'Cartographic shaders',
    body: 'The GPU code behind a map — a graticule, shaded relief, a choropleth colour ramp. Procedural, so they render with no data and no tiles.',
  },
  {
    key: 'generic' as const,
    title: 'General shaders',
    body: 'The DSL is content-free: the same authoring surface, used as a plain shader toolkit.',
  },
  {
    key: 'compute' as const,
    title: 'Compute (WebGPU)',
    body: 'GPGPU kernels. GLSL ES 3.00 has no compute, so the DSL fails closed for WebGL2 — these show the WGSL + reflection face of the same source.',
  },
]
