// ═══ GLSL ES 3.00 gate — INTEGER sampled textures + the array<u32> storage lowering (#1703) ═══
//
// The sibling _glsl-texture-gate covers `sampler2D` and _glsl-texture-array-gate covers
// `sampler2DArray`. This one covers the ELEMENT axis: `usampler2D` / `isampler2D`, whose
// whole reason to exist is that the texel arrives EXACT.
//
// WHY A REAL DRIVER IS REQUIRED HERE. A unit test can prove the emitted string says
// `usampler2D`, and glsl.test.ts does. It cannot prove the two properties this feature
// actually rests on:
//
//   1. The shader COMPILES. GLSL ES 3.00 §4.5.4 predeclares default precisions for
//      `sampler2D` / `samplerCube` ONLY, so an unqualified `uniform usampler2D` is a hard
//      compile error. The emitter derives a `precision highp usampler2D;` line for it —
//      a rule with no unit-visible consequence whatsoever, because the string looks fine
//      either way. Only a driver rejects it.
//   2. The value SURVIVES. This is the whole argument for typed textures over the
//      bitcast-lane scheme (carry u32s through the existing R32F data texture and recover
//      them with floatBitsToUint). GLSL ES 3.00 §2.1.1: "Any denormalized value input into
//      a shader or potentially generated by any operation in a shader can be flushed to 0."
//      Small integers ARE denormal f32 bit patterns — `1u` is 1.4e-45.
//
// THE DISCRIMINATION TABLE. Each output channel carries ONE texel's exact-match verdict:
//
//   r ← ids[0] == 1u          (0x00000001) — DENORMAL as f32
//   g ← ids[1] == 0xFFFFFFFFu              — a NaN payload as f32
//   b ← ids[2] == 0x007FFFFFu              — the LARGEST denormal, the boundary case
//   a ← ids[3] == 0xDEADBEEFu              — a normal, finite f32 bit pattern (control)
//
// (255,255,255,255) = every texel exact. (128,128,128,255) = nothing drew (the clear
// colour), which is distinct from every wrong-value outcome.
//
// WHAT THIS GATE DOES AND DOES NOT PROVE — measured, not assumed (§12). A probe run
// against THIS CI driver (SwiftShader, reported as "WebKit WebGL") uploaded the same four
// bit patterns through an R32F texture and recovered them with floatBitsToUint: all four
// came back EXACT. So SwiftShader does not exercise its §2.1.1 right to flush denormals,
// and these values do NOT locally discriminate typed-texture from bitcast-lane. They are
// kept because they cost nothing and would catch it on a driver that does flush — but the
// argument for typed textures is a SPEC argument (a conforming implementation MAY flush,
// so the bitcast route is unsound everywhere it has not been measured), not something a
// green run here establishes. Claiming otherwise would be an assertion that passes
// identically under the fault it names.
//
// What a mutation probe DID confirm this gate catches: severing the emitter's
// `precision highp <sampler>;` derivation turns all four tests red, and test 1 fails with
// the DRIVER REJECTING the shader — the property no unit test can reach.
//
// Test 3 drives the SAME properties through the storage→data-texture lowering, which is
// the consumer this was built for: `var<storage, read> ids: array<u32>` on WebGL2 has no
// SSBO to live in, so it lowers to exactly this usampler2D + texelFetch, backed by an
// R32UI texture the host allocates. Binding an R32F texture there does not error — the
// texture is merely INCOMPLETE and texelFetch silently returns 0 — which is why the
// end-to-end leg exists at all.

// Relative deep import (charter): Playwright transpiles specs in raw Node — the @xgis/* workspace alias does not resolve here, so specs import package SOURCES relatively (see _glsl-compile-gate.spec.ts).
import { test, expect } from '@playwright/test'
import {
  emitGlslModule,
  fn,
  module as dslModule,
  ioStruct,
  builtin,
  location,
  resource,
  storageBuffer,
  select,
  textureLoad,
  textureDimensions,
  vec2i,
  vec4,
  u32,
  i32,
  texture2duT,
  texture2diT,
  vec2fT,
  vec4fT,
  u32T,
  type ModuleDecl,
} from '../../shader-dsl/src/index'

// ── the direct integer-texture module ──
const IntOut = ioStruct('IntOut', { pos: builtin('position', vec4fT), uv: location(0, vec2fT) })
const ids = resource('ids', texture2duT, { group: 0, binding: 0 })
const deltas = resource('deltas', texture2diT, { group: 0, binding: 1 })

const intVs = fn(
  'vs',
  { pos: location(0, vec2fT) },
  ({ pos }) => {
    const o = IntOut.var('out')
    o.pos.assign(vec4(pos.x, pos.y, 0, 1))
    o.uv.assign(pos)
    return o
  },
  { stage: 'vertex' },
)

/** `1.0` when texel `i` of `ids` equals `want`, else `0.0` — one channel, one verdict. */
const idsMatch = (i: number, want: number) =>
  select(textureLoad(ids.node, vec2i(i, 0), 0).x.eq(u32(want)), 1, 0)

const intFs = fn(
  'fs',
  { inp: IntOut },
  () =>
    vec4(
      idsMatch(0, 0x00000001), // denormal as f32 — the discriminator
      idsMatch(1, 0xffffffff), // NaN payload as f32
      idsMatch(2, 0x007fffff), // largest denormal
      idsMatch(3, 0xdeadbeef), // normal f32 pattern — the control
    ),
  { stage: 'fragment', retAttr: location(0, vec4fT) },
)

const intModule: ModuleDecl = dslModule({ uses: [IntOut, ids, deltas], funcs: [intVs, intFs] })

// ── the SIGNED module: negatives are the property an unsigned path cannot fake ──
const signedFs = fn(
  'fs',
  { inp: IntOut },
  () =>
    vec4(
      select(textureLoad(deltas.node, vec2i(0, 0), 0).x.eq(i32(-1)), 1, 0),
      select(textureLoad(deltas.node, vec2i(1, 0), 0).x.eq(i32(-2147483648)), 1, 0),
      // textureDimensions is element-BLIND — 4×1, so x-y = 3 witnesses both components.
      select(
        textureDimensions(deltas.node).x.sub(textureDimensions(deltas.node).y).eq(u32(3)),
        1,
        0,
      ),
      1,
    ),
  { stage: 'fragment', retAttr: location(0, vec4fT) },
)
const signedModule: ModuleDecl = dslModule({
  uses: [IntOut, ids, deltas],
  funcs: [intVs, signedFs],
})

// ── the STORAGE module: `array<u32>` with NO texture in the authored source ──
// The author writes a storage buffer; WebGL2's lowering is what produces the usampler2D.
const storeVs = fn(
  'vs',
  { pos: location(0, vec2fT) },
  ({ pos }) => {
    const o = IntOut.var('out')
    o.pos.assign(vec4(pos.x, pos.y, 0, 1))
    o.uv.assign(pos)
    return o
  },
  { stage: 'vertex' },
)
const storeBuf = storageBuffer('feat_ids', u32T, { group: 0, binding: 0, access: 'read' })
const storeFs = fn(
  'fs',
  { inp: IntOut },
  () =>
    vec4(
      select(storeBuf.at(0).eq(u32(0x00000001)), 1, 0),
      select(storeBuf.at(1).eq(u32(0xffffffff)), 1, 0),
      select(storeBuf.at(2).eq(u32(0x007fffff)), 1, 0),
      select(storeBuf.at(3).eq(u32(0xdeadbeef)), 1, 0),
    ),
  { stage: 'fragment', retAttr: location(0, vec4fT) },
)
const storageModule: ModuleDecl = dslModule({
  uses: [IntOut, storeBuf],
  funcs: [storeVs, storeFs],
})

// The four probe values, in texel order. Shared by every leg so the shader's expectations
// and the uploaded bytes cannot drift apart.
const PROBE_U32 = [0x00000001, 0xffffffff, 0x007fffff, 0xdeadbeef]

/** Page-side: compile+link a GLSL ES 3.00 pair, upload an R32UI/R32I 4×1 data texture,
 *  draw a fullscreen quad, read back the centre pixel. Returns the RGBA + any GL error. */
const DRAW_INTEGER_TEXTURE = ({
  vertex,
  fragment,
  uniforms,
}: {
  vertex: string
  fragment: string
  uniforms: readonly { name: string; signed: boolean; values: readonly number[] }[]
}) => {
  const canvas = document.createElement('canvas')
  canvas.width = 4
  canvas.height = 4
  const gl = canvas.getContext('webgl2', { preserveDrawingBuffer: true })
  if (!gl) return { fatal: 'no webgl2' as const }
  const compile = (type: number, src: string) => {
    const sh = gl.createShader(type)!
    gl.shaderSource(sh, src)
    gl.compileShader(sh)
    return {
      ok: gl.getShaderParameter(sh, gl.COMPILE_STATUS) as boolean,
      log: gl.getShaderInfoLog(sh) ?? '',
      sh,
    }
  }
  const vs = compile(gl.VERTEX_SHADER, vertex)
  const fs = compile(gl.FRAGMENT_SHADER, fragment)
  if (!vs.ok || !fs.ok) return { fatal: 'compile' as const, vsLog: vs.log, fsLog: fs.log }
  const prog = gl.createProgram()!
  gl.attachShader(prog, vs.sh)
  gl.attachShader(prog, fs.sh)
  gl.linkProgram(prog)
  if (!gl.getProgramParameter(prog, gl.LINK_STATUS))
    return { fatal: 'link' as const, linkLog: gl.getProgramInfoLog(prog) ?? '' }

  gl.useProgram(prog)
  uniforms.forEach((u, unit) => {
    const tex = gl.createTexture()
    gl.activeTexture(gl.TEXTURE0 + unit)
    gl.bindTexture(gl.TEXTURE_2D, tex)
    // R32UI / R32I — the formats the emitted usampler2D / isampler2D require. An R32F
    // texture here would leave the texture INCOMPLETE and every texelFetch would read 0.
    const n = u.values.length
    gl.texImage2D(
      gl.TEXTURE_2D,
      0,
      u.signed ? gl.R32I : gl.R32UI,
      n,
      1,
      0,
      gl.RED_INTEGER,
      u.signed ? gl.INT : gl.UNSIGNED_INT,
      u.signed ? new Int32Array(u.values) : new Uint32Array(u.values),
    )
    // Integer textures are UNFILTERABLE — a LINEAR filter makes them incomplete.
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.NEAREST)
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.NEAREST)
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE)
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE)
    gl.uniform1i(gl.getUniformLocation(prog, u.name), unit)
  })

  const buf = gl.createBuffer()
  gl.bindBuffer(gl.ARRAY_BUFFER, buf)
  // prettier-ignore
  gl.bufferData(gl.ARRAY_BUFFER, new Float32Array([
    -1, -1,  1, -1,  -1, 1,
    -1,  1,  1, -1,   1, 1,
  ]), gl.STATIC_DRAW)
  gl.enableVertexAttribArray(0)
  gl.vertexAttribPointer(0, 2, gl.FLOAT, false, 8, 0)

  gl.viewport(0, 0, 4, 4)
  // 50% grey, alpha 1 — a pixel that stays (128,128,128,255) means nothing drew.
  gl.clearColor(0.5, 0.5, 0.5, 1)
  gl.clear(gl.COLOR_BUFFER_BIT)
  gl.drawArrays(gl.TRIANGLES, 0, 6)

  const px = new Uint8Array(4)
  gl.readPixels(2, 2, 1, 1, gl.RGBA, gl.UNSIGNED_BYTE, px)
  return { px: [px[0], px[1], px[2], px[3]], glError: gl.getError() }
}

test('the integer-texture module compiles + links on real WebGL2 (usampler2D / isampler2D)', async ({
  page,
}) => {
  const vertex = emitGlslModule(intModule, 'vertex')
  const fragment = emitGlslModule(intModule, 'fragment')

  // Emit shape first, so a failure below is attributable: a broken SPELLING and a broken
  // driver interaction produce the same red without this.
  expect(fragment).toContain('uniform usampler2D ids;')
  expect(fragment).toContain('texelFetch(ids,')
  // …and the §4.5.4 precision line without which none of it compiles.
  expect(fragment).toContain('precision highp usampler2D;')
  // `deltas` is declared by the MODULE but read by no function in this stage, so
  // per-stage emit scopes it out — and with it, its precision line. That is the
  // #1651 stage-scoping rule holding on the element axis too.
  expect(fragment).not.toContain('isampler2D')

  await page.goto('/demo.html?id=minimal', { waitUntil: 'domcontentloaded' })
  const result = await page.evaluate(DRAW_INTEGER_TEXTURE, {
    vertex,
    fragment,
    uniforms: [
      { name: 'ids', signed: false, values: PROBE_U32 },
      { name: 'deltas', signed: true, values: [-1, -2147483648, 0, 0] },
    ],
  })
  expect(result, 'WebGL2 unavailable / shader rejected').not.toHaveProperty('fatal')
})

test('u32 texels arrive EXACT — including the denormal bit patterns a float lane would lose', async ({
  page,
}) => {
  const vertex = emitGlslModule(intModule, 'vertex')
  const fragment = emitGlslModule(intModule, 'fragment')
  await page.goto('/demo.html?id=minimal', { waitUntil: 'domcontentloaded' })
  const result = await page.evaluate(DRAW_INTEGER_TEXTURE, {
    vertex,
    fragment,
    uniforms: [
      { name: 'ids', signed: false, values: PROBE_U32 },
      { name: 'deltas', signed: true, values: [-1, -2147483648, 0, 0] },
    ],
  })
  expect(result, 'WebGL2 unavailable / shader rejected').not.toHaveProperty('fatal')
  if ('fatal' in result) return
  expect(result.glError, 'gl error during the integer-texture draw').toBe(0)
  const [r, g, b, a] = result.px
  expect(
    { r, g, b, a },
    `each channel is one texel's exact-match verdict: r=ids[0]==1u (denormal as f32), ` +
      `g=ids[1]==0xFFFFFFFF (NaN payload), b=ids[2]==0x007FFFFF (largest denormal), ` +
      `a=ids[3]==0xDEADBEEF (a normal f32 pattern). A zero in ANY channel means the ` +
      `usampler2D read did not deliver the uploaded R32UI texel. ` +
      `(128,128,128,255) = nothing drew`,
  ).toEqual({ r: 255, g: 255, b: 255, a: 255 })
})

test('i32 texels keep their SIGN, and textureDimensions reads an integer texture', async ({
  page,
}) => {
  const vertex = emitGlslModule(signedModule, 'vertex')
  const fragment = emitGlslModule(signedModule, 'fragment')
  expect(fragment).toContain('uniform isampler2D deltas;')
  expect(fragment).toContain('precision highp isampler2D;')
  expect(fragment).toContain('uvec2(textureSize(deltas, 0))')

  await page.goto('/demo.html?id=minimal', { waitUntil: 'domcontentloaded' })
  const result = await page.evaluate(DRAW_INTEGER_TEXTURE, {
    vertex,
    fragment,
    uniforms: [
      { name: 'ids', signed: false, values: PROBE_U32 },
      { name: 'deltas', signed: true, values: [-1, -2147483648, 7, 7] },
    ],
  })
  expect(result, 'WebGL2 unavailable / shader rejected').not.toHaveProperty('fatal')
  if ('fatal' in result) return
  expect(result.glError, 'gl error during the signed-texture draw').toBe(0)
  const [r, g, b] = result.px
  expect(
    { r, g, b },
    `r=deltas[0]==-1, g=deltas[1]==INT_MIN (the value an unsigned path cannot represent), ` +
      `b=textureDimensions(deltas) is 4×1. A zero in r/g means the signed sampler read ` +
      `through the wrong element type`,
  ).toEqual({ r: 255, g: 255, b: 255 })
})

test('a `var<storage, read> array<u32>` lowers to the same exact usampler2D read end to end', async ({
  page,
}) => {
  // The authored module names NO texture — the storage→data-texture lowering produces it,
  // which is the path #1592's per-feature data would take on WebGL2.
  const vertex = emitGlslModule(storageModule, 'vertex')
  const fragment = emitGlslModule(storageModule, 'fragment')
  expect(fragment).toContain('uniform usampler2D feat_ids;')
  expect(fragment).toContain('precision highp usampler2D;')
  expect(fragment).not.toContain('floatBitsToUint') // no bitcast lane survived
  expect(fragment).not.toContain('uniform sampler2D feat_ids;')

  await page.goto('/demo.html?id=minimal', { waitUntil: 'domcontentloaded' })
  const result = await page.evaluate(DRAW_INTEGER_TEXTURE, {
    vertex,
    fragment,
    uniforms: [{ name: 'feat_ids', signed: false, values: PROBE_U32 }],
  })
  expect(result, 'WebGL2 unavailable / shader rejected').not.toHaveProperty('fatal')
  if ('fatal' in result) return
  expect(result.glError, 'gl error during the storage-lowering draw').toBe(0)
  const [r, g, b, a] = result.px
  expect(
    { r, g, b, a },
    `the lowered array<u32> must deliver the same four exact values as the direct ` +
      `texture read. Any zero here with the direct test green means the LOWERING ` +
      `(index math or sampler choice), not the texture surface, is at fault`,
  ).toEqual({ r: 255, g: 255, b: 255, a: 255 })
})
