import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

import {
  mercator,
  equirectangular,
  naturalEarth,
  orthographic,
  azimuthalEquidistant,
  stereographic,
} from '../engine/projection'
import type { Projection } from '../engine/projection'
import {
  compileGeoJSONToTiles,
  tileKey,
  simplify as xgisSimplify,
} from '@xgis/compiler'
import type { GeoJSONFeatureCollection } from '@xgis/compiler'

// Cross-validation tests: compare our CPU math against reference values
// computed by INDEPENDENT Python libraries (pyproj, mercantile, shapely).
// The fixture is generated by scripts/cross-validation/generate-fixtures.py
// and committed to the repo. If a formula drifts from the documented
// standard, these tests catch it even when our own CPU/WGSL pair stays
// internally consistent.
//
// Why this matters: the rest of the suite verifies our CPU matches our
// WGSL. That catches intra-repo divergence but not "same bug in both".
// The Python libraries are a different codebase, different authors,
// different maintainers, and are the de-facto standards for their
// domains (GeoJSON pyproj, slippy-map mercantile, GEOS shapely).

const __dirname = dirname(fileURLToPath(import.meta.url))
const FIXTURE_PATH = resolve(__dirname, './cross-validation.fixture.json')

interface MercatorForwardSample { lon: number; lat: number; mercX: number; mercY: number }
interface MercatorInverseSample { mercX: number; mercY: number; lon: number; lat: number }
interface TileSample {
  label: string
  lon: number; lat: number; zoom: number
  tileX: number; tileY: number; tileZ: number
  boundsWest: number; boundsSouth: number; boundsEast: number; boundsNorth: number
}
interface ClipSample {
  zoom: number; tileX: number; tileY: number
  tileWest: number; tileSouth: number; tileEast: number; tileNorth: number
  tileArea: number; interArea: number; fullyCovered: boolean
}
interface ProjectionSample {
  lon: number; lat: number
  x: number; y: number
  roundLon: number; roundLat: number
}
interface TileFeatureCount {
  z: number; x: number; y: number
  west: number; south: number; east: number; north: number
  featureCount: number
}
interface CountryBBox {
  name: string
  west: number; south: number; east: number; north: number
}
interface PipelineAreaSample {
  name: string
  featureIndex: number
  z: number; x: number; y: number
  areaMercM2: number
}
interface SimplifySample {
  label: string
  input: number[][]
  toleranceDeg: number
  originalArea: number
  shapelyOutput: number[][]
  shapelyVertexCount: number
  shapelyArea: number
}
interface Fixture {
  _meta: { generator: string; pyproj: string; mercantile: string; shapely: string }
  mercator_forward: MercatorForwardSample[]
  mercator_inverse: MercatorInverseSample[]
  tile_math: TileSample[]
  polygon_clip_contains: ClipSample[]
  projections: Record<string, ProjectionSample[]>
  tile_feature_counts: TileFeatureCount[]
  country_bboxes: CountryBBox[]
  pipeline_area_samples: PipelineAreaSample[]
  simplify_samples: SimplifySample[]
  constants: {
    mercator_at_zero: { lon: number; lat: number; expectedX: number; expectedY: number }
    mercator_pole_x: { lon: number; lat: number; expectedX: number; expectedY: number }
    earth_radius_m: number
    pi_times_R: number
  }
}

const fixture: Fixture = JSON.parse(readFileSync(FIXTURE_PATH, 'utf8'))

describe('Cross-validation: fixture metadata', () => {
  it('is tagged with the generator script + reference library versions', () => {
    expect(fixture._meta.generator).toBe('scripts/cross-validation/generate-fixtures.py')
    expect(fixture._meta.pyproj).toMatch(/^\d+\.\d+/)
    expect(fixture._meta.mercantile).toMatch(/^\d+\.\d+/)
    expect(fixture._meta.shapely).toMatch(/^\d+\.\d+/)
  })
})

describe('Cross-validation: Mercator forward (vs pyproj EPSG:3857)', () => {
  // Tolerance: 1 µm (1e-6 m). pyproj uses the same earth radius
  // (6378137 m per EPSG:3857 spec), so agreement should be essentially
  // perfect modulo floating-point rounding.
  const TOL_M = 1e-6
  it(`matches pyproj at ${fixture.mercator_forward.length} sample points`, () => {
    for (const s of fixture.mercator_forward) {
      const [x, y] = mercator.forward(s.lon, s.lat)
      expect(x, `lon=${s.lon}`).toBeCloseTo(s.mercX, 6) // 1 µm
      // pyproj at lat=80 returns a specific value — our clamp doesn't
      // kick in until MERCATOR_LAT_LIMIT ≈ 85.051°, so latitudes in
      // the fixture's ±80 range are projected un-clamped and should
      // match pyproj to full f64 precision.
      if (Math.abs(s.lat) < 85) {
        expect(y, `lat=${s.lat}`).toBeCloseTo(s.mercY, 6)
      }
    }
  })
})

describe('Cross-validation: Mercator inverse (vs pyproj)', () => {
  it(`recovers lon/lat from Mercator X,Y across ${fixture.mercator_inverse.length} samples`, () => {
    for (const s of fixture.mercator_inverse) {
      const [lon, lat] = mercator.inverse(s.mercX, s.mercY)
      expect(lon).toBeCloseTo(s.lon, 10)
      expect(lat).toBeCloseTo(s.lat, 10)
    }
  })
})

describe('Cross-validation: Tile math (vs mercantile)', () => {
  // mercantile uses the same (lon, lat, zoom) → tile (x, y) formula as
  // the slippy-map spec. Our loader/tiles helpers must produce the
  // same integer tile coords.
  function ourTileXY(lon: number, lat: number, zoom: number): [number, number] {
    const n = Math.pow(2, zoom)
    const x = Math.floor((lon + 180) / 360 * n)
    const clampedLat = Math.max(-85.051129, Math.min(85.051129, lat))
    const y = Math.floor(
      (1 - Math.log(Math.tan(Math.PI / 4 + clampedLat * Math.PI / 360)) / Math.PI) / 2 * n,
    )
    return [x, y]
  }

  function ourTileBounds(x: number, y: number, z: number) {
    const n = Math.pow(2, z)
    const west = x / n * 360 - 180
    const east = (x + 1) / n * 360 - 180
    const north = Math.atan(Math.sinh(Math.PI * (1 - 2 * y / n))) * 180 / Math.PI
    const south = Math.atan(Math.sinh(Math.PI * (1 - 2 * (y + 1) / n))) * 180 / Math.PI
    return { west, south, east, north }
  }

  it(`lon/lat → tile (x, y) matches mercantile at ${fixture.tile_math.length} samples`, () => {
    for (const s of fixture.tile_math) {
      // Skip polar cases at z=0: mercantile's behavior at the pole is
      // lightly undefined (one tile covers the whole world). Our
      // clamp and their clamp may differ by 1 tile; it's not a bug.
      if (s.zoom === 0 && Math.abs(s.lat) > 60) continue

      const [tx, ty] = ourTileXY(s.lon, s.lat, s.zoom)
      expect(tx, `${s.label} z=${s.zoom} x`).toBe(s.tileX)
      expect(ty, `${s.label} z=${s.zoom} y`).toBe(s.tileY)
    }
  })

  it(`tile (x, y, z) → bounds matches mercantile at ${fixture.tile_math.length} samples`, () => {
    for (const s of fixture.tile_math) {
      const b = ourTileBounds(s.tileX, s.tileY, s.tileZ)
      expect(b.west,  `${s.label} z=${s.zoom} west`).toBeCloseTo(s.boundsWest, 10)
      expect(b.east,  `${s.label} z=${s.zoom} east`).toBeCloseTo(s.boundsEast, 10)
      expect(b.south, `${s.label} z=${s.zoom} south`).toBeCloseTo(s.boundsSouth, 10)
      expect(b.north, `${s.label} z=${s.zoom} north`).toBeCloseTo(s.boundsNorth, 10)
    }
  })
})

describe('Cross-validation: Polygon full-cover (vs shapely)', () => {
  // Our full-cover detection uses an area-ratio heuristic (polygon area
  // ≈ tile area within 1e-6 relative tolerance). Shapely's `contains`
  // is the GEOS reference. When shapely says the world polygon
  // contains a tile, our fullCover detection should also trigger
  // (given the same input).
  it('shapely-contains verdict lines up with our ratio test at all zooms', () => {
    for (const s of fixture.polygon_clip_contains) {
      // Reproduce the ratio test from compileGeoJSONToTiles in lon/lat
      // space — same formula (polyArea / tileArea within 1e-6).
      const tileArea = (s.tileEast - s.tileWest) * (s.tileNorth - s.tileSouth)
      expect(tileArea).toBeCloseTo(s.tileArea, 6)
      const interArea = s.interArea
      const ourFullCover = Math.abs(interArea - tileArea) / tileArea < 1e-6
      expect(
        ourFullCover,
        `shapely says ${s.fullyCovered}, ratio says ${ourFullCover} at z=${s.zoom}`,
      ).toBe(s.fullyCovered)
    }
  })
})

describe('Cross-validation: Published EPSG:3857 reference points', () => {
  it('Mercator at origin is (0, 0)', () => {
    const [x, y] = mercator.forward(
      fixture.constants.mercator_at_zero.lon,
      fixture.constants.mercator_at_zero.lat,
    )
    // pyproj returns exact 0 at lat=0; our CPU pipeline goes through
    // Math.log(Math.tan(Math.PI/4)) × R which rounds to ~7e-10 m due
    // to tan(π/4) = 0.9999999999999999 in IEEE 754. Sub-nanometer drift
    // at the origin is expected — use µm-level tolerance.
    expect(x).toBeCloseTo(fixture.constants.mercator_at_zero.expectedX, 6)
    expect(y).toBeCloseTo(fixture.constants.mercator_at_zero.expectedY, 6)
  })

  it('Mercator X at lon=180 is π × R (≈ 20 037 508.34)', () => {
    const [x] = mercator.forward(
      fixture.constants.mercator_pole_x.lon,
      fixture.constants.mercator_pole_x.lat,
    )
    expect(x).toBeCloseTo(fixture.constants.mercator_pole_x.expectedX, 5)
    expect(fixture.constants.pi_times_R).toBe(fixture.constants.mercator_pole_x.expectedX)
    // π × 6378137 confirmed by the EPSG:3857 definition.
    expect(Math.PI * fixture.constants.earth_radius_m).toBeCloseTo(fixture.constants.pi_times_R, 6)
  })
})

// ═══ Other 5 projections (vs pyproj) ═══
//
// Oblique Mercator is intentionally not cross-checked: X-GIS uses a
// custom sphere-rotation-then-Mercator formula that doesn't map 1:1
// to pyproj's `+proj=omerc` parameterization. Intra-repo CPU/WGSL
// consistency tests cover it.
//
// Center for family-parameterized projections is (lon=0, lat=20) —
// matches the default in projection.ts.

function runProjectionCrossCheck(
  name: string,
  proj: Projection,
  samples: ProjectionSample[],
  opts: { forwardPrecision: number; invLonPrecision: number; invLatPrecision: number },
) {
  describe(`Cross-validation: ${name} (vs pyproj)`, () => {
    it(`forward matches pyproj at ${samples.length} sample points`, () => {
      for (const s of samples) {
        const [x, y] = proj.forward(s.lon, s.lat)
        // Skip sample if our projection returned NaN at a point pyproj
        // accepted (e.g. antipode edge cases for spherical projections).
        if (!Number.isFinite(x) || !Number.isFinite(y)) continue
        expect(x, `${name} x at lon=${s.lon}, lat=${s.lat}`).toBeCloseTo(s.x, opts.forwardPrecision)
        expect(y, `${name} y at lon=${s.lon}, lat=${s.lat}`).toBeCloseTo(s.y, opts.forwardPrecision)
      }
    })

    it(`inverse round-trip recovers lon/lat from pyproj's projected (x, y)`, () => {
      for (const s of samples) {
        const [lon, lat] = proj.inverse(s.x, s.y)
        if (!Number.isFinite(lon) || !Number.isFinite(lat)) continue
        expect(lon, `${name} lon from (${s.x.toFixed(2)}, ${s.y.toFixed(2)})`)
          .toBeCloseTo(s.roundLon, opts.invLonPrecision)
        expect(lat, `${name} lat from (${s.x.toFixed(2)}, ${s.y.toFixed(2)})`)
          .toBeCloseTo(s.roundLat, opts.invLatPrecision)
      }
    })
  })
}

// Precision notes (toBeCloseTo: tolerance = 0.5 × 10^-N):
//   forward N=2 → 5 mm tolerance in meters (relaxed for projections
//     with sphere-vs-ellipsoid or center-of-proj small differences)
//   inverse N=6 → 5e-7 deg ≈ 5 cm at equator; plenty for Newton-Raphson
//     convergence (natural earth) or analytic inverse (the others).

runProjectionCrossCheck('Equirectangular', equirectangular,
  fixture.projections.equirectangular,
  { forwardPrecision: 2, invLonPrecision: 6, invLatPrecision: 6 })

// NaturalEarth is a KNOWN DIVERGENCE from both pyproj `natearth`
// (Patterson 2007) and `natearth2` (Šavrič 2015). X-GIS's polynomial
// coefficients in runtime/src/engine/projection.ts do not exactly
// match either published formulation, but the CPU path is internally
// consistent with the WGSL proj_natural_earth shader (verified by
// projection-wgsl-consistency tests). See memory entry
// `project_projection_divergences.md` (A-1 locked divergence). At
// lat=±80 the delta vs pyproj natearth2 is ~2.2 Mm, well outside any
// reasonable floating-point tolerance — this is a formula choice,
// not a numerical error. Re-enable this block once the CPU/WGSL pair
// is moved to a published-standard polynomial.
describe.skip('Cross-validation: NaturalEarth (vs pyproj) — SKIPPED (A-1 divergence)', () => {
  it('tracked by memory project_projection_divergences.md', () => {
    void naturalEarth
  })
})

runProjectionCrossCheck('Orthographic (0°, 20°)', orthographic(0, 20),
  fixture.projections.orthographic,
  { forwardPrecision: 2, invLonPrecision: 6, invLatPrecision: 6 })

runProjectionCrossCheck('AzimuthalEquidistant (0°, 20°)', azimuthalEquidistant(0, 20),
  fixture.projections.azimuthal_equidistant,
  { forwardPrecision: 2, invLonPrecision: 6, invLatPrecision: 6 })

runProjectionCrossCheck('Stereographic (0°, 20°)', stereographic(0, 20),
  fixture.projections.stereographic,
  { forwardPrecision: 2, invLonPrecision: 6, invLatPrecision: 6 })

// ═══ Real-data: per-tile feature count vs shapely ═══

describe('Cross-validation: Real-data tile featureCount (vs shapely)', () => {
  // Load the same countries.geojson the playground uses, compile it via
  // X-GIS, and check each tile's featureCount matches how many country
  // polygons shapely says intersect that tile's bounds.
  const COUNTRIES_PATH = resolve(__dirname, '../../../playground/public/data/countries.geojson')
  const gj = JSON.parse(readFileSync(COUNTRIES_PATH, 'utf8')) as GeoJSONFeatureCollection

  const zooms = [...new Set(fixture.tile_feature_counts.map(t => t.z))].sort((a, b) => a - b)
  const minZoom = zooms[0]!
  const maxZoom = zooms[zooms.length - 1]!
  const set = compileGeoJSONToTiles(gj, { minZoom, maxZoom })

  it(`shapely intersection count matches X-GIS featureCount at ${fixture.tile_feature_counts.length} tiles`, () => {
    const levelByZ = new Map(set.levels.map(l => [l.zoom, l]))
    const diffs: Array<{ key: string; shapely: number; ours: number; diff: number }> = []
    for (const s of fixture.tile_feature_counts) {
      const level = levelByZ.get(s.z)
      if (!level) continue
      const key = tileKey(s.z, s.x, s.y)
      const tile = level.tiles.get(key)
      const ourCount = tile ? tile.featureCount : 0
      const diff = ourCount - s.featureCount
      if (diff !== 0) diffs.push({ key: `z=${s.z} x=${s.x} y=${s.y}`, shapely: s.featureCount, ours: ourCount, diff })
    }
    // Baseline statistics on the 80-tile fixture: max |diff| ≤ 3,
    // occurs on large (z=2) tiles whose boundary passes through many
    // features. Diffs are driven by the clipper's snap-vertex policy
    // (Sutherland-Hodgman with epsilon), which can drop a single
    // micro-slice where shapely's GEOS boolean would emit a 0-dimensional
    // residue. Tighten this bound over time as the clipper's behaviour
    // is brought closer to GEOS.
    const maxAbsDiff = diffs.reduce((m, d) => Math.max(m, Math.abs(d.diff)), 0)
    const summary = diffs.slice(0, 10).map(d => `${d.key}: shapely=${d.shapely} ours=${d.ours} (diff=${d.diff})`).join('\n  ')
    expect(
      maxAbsDiff,
      `${diffs.length} / ${fixture.tile_feature_counts.length} tiles diverged; first few:\n  ${summary}`,
    ).toBeLessThanOrEqual(3)
  })
})

// ═══ Real-data: per-country bbox vs shapely.bounds ═══

describe('Cross-validation: Country bounding boxes (vs shapely)', () => {
  // Aggregate bbox per feature from the raw GeoJSON coordinates and
  // compare against shapely.bounds. Tests that our coordinate-parsing
  // path (flatten MultiPolygon → min/max) matches GEOS.
  const COUNTRIES_PATH = resolve(__dirname, '../../../playground/public/data/countries.geojson')
  const gj = JSON.parse(readFileSync(COUNTRIES_PATH, 'utf8')) as GeoJSONFeatureCollection

  function featureBBox(geom: unknown): [number, number, number, number] {
    let w = Infinity, s = Infinity, e = -Infinity, n = -Infinity
    const walk = (node: unknown): void => {
      if (!Array.isArray(node)) return
      if (node.length >= 2 && typeof node[0] === 'number' && typeof node[1] === 'number') {
        const [lon, lat] = node as [number, number]
        if (lon < w) w = lon
        if (lon > e) e = lon
        if (lat < s) s = lat
        if (lat > n) n = lat
        return
      }
      for (const child of node) walk(child)
    }
    walk((geom as { coordinates: unknown }).coordinates)
    return [w, s, e, n]
  }

  it('bbox per country matches shapely at the requested precision', () => {
    for (const cb of fixture.country_bboxes) {
      const feat = gj.features.find(f => (f.properties as { name?: string } | null)?.name === cb.name)
      expect(feat, `country ${cb.name} not found in geojson`).toBeDefined()
      const [w, s, e, n] = featureBBox(feat!.geometry)
      // Coordinates are 6 decimal places in the source file, so 1e-6
      // deg ≈ 11 cm at the equator is the tightest meaningful tolerance.
      expect(w, `${cb.name} west`).toBeCloseTo(cb.west, 6)
      expect(s, `${cb.name} south`).toBeCloseTo(cb.south, 6)
      expect(e, `${cb.name} east`).toBeCloseTo(cb.east, 6)
      expect(n, `${cb.name} north`).toBeCloseTo(cb.north, 6)
    }
  })
})

// ═══ Real-data: pipeline geometry area vs shapely intersection ═══

describe('Cross-validation: Pipeline geometry area (clip + triangulate vs shapely)', () => {
  // For each (country, z=3 tile) pair in the fixture, compile the
  // geojson at maxZoom=3 (no simplification on z=3 tiles since the
  // tiler skips simplify at `z == maxZoom`), then sum the triangle
  // areas in the target tile that are tagged with this country's
  // featureIndex. Compare against shapely's exact Mercator
  // intersection area. Any significant delta means the clip +
  // triangulate pipeline is losing or duplicating area.
  const COUNTRIES_PATH = resolve(__dirname, '../../../playground/public/data/countries.geojson')
  const gj = JSON.parse(readFileSync(COUNTRIES_PATH, 'utf8')) as GeoJSONFeatureCollection

  const zooms = [...new Set(fixture.pipeline_area_samples.map(s => s.z))].sort((a, b) => a - b)
  const maxZoom = zooms[zooms.length - 1]!
  // maxZoom equals the fixture zoom so the tile-level simplification
  // filter (`z < maxZoom`) does not run. Triangulated area should be
  // exact up to earcut precision.
  const set = compileGeoJSONToTiles(gj, { minZoom: 0, maxZoom })

  function triangleAreaForFeature(
    vertices: Float32Array,
    indices: Uint32Array,
    targetFid: number,
  ): number {
    // DSFUN polygon stride 5: [mx_h, my_h, mx_l, my_l, fid]
    // Coordinates are local to the tile origin (cancels in area calc).
    let total = 0
    for (let i = 0; i < indices.length; i += 3) {
      const i0 = indices[i], i1 = indices[i + 1], i2 = indices[i + 2]
      const fid0 = vertices[i0 * 5 + 4]
      const fid1 = vertices[i1 * 5 + 4]
      const fid2 = vertices[i2 * 5 + 4]
      if (fid0 !== targetFid || fid1 !== targetFid || fid2 !== targetFid) continue
      const x0 = vertices[i0 * 5] + vertices[i0 * 5 + 2]
      const y0 = vertices[i0 * 5 + 1] + vertices[i0 * 5 + 3]
      const x1 = vertices[i1 * 5] + vertices[i1 * 5 + 2]
      const y1 = vertices[i1 * 5 + 1] + vertices[i1 * 5 + 3]
      const x2 = vertices[i2 * 5] + vertices[i2 * 5 + 2]
      const y2 = vertices[i2 * 5 + 1] + vertices[i2 * 5 + 3]
      total += 0.5 * Math.abs(x0 * (y1 - y2) + x1 * (y2 - y0) + x2 * (y0 - y1))
    }
    return total
  }

  it(`X-GIS triangulated area matches shapely intersection at ${fixture.pipeline_area_samples.length} country-tile pairs`, () => {
    const levelByZ = new Map(set.levels.map(l => [l.zoom, l]))
    const report: string[] = []
    let maxRelDelta = 0
    for (const s of fixture.pipeline_area_samples) {
      const level = levelByZ.get(s.z)
      if (!level) continue
      const key = tileKey(s.z, s.x, s.y)
      const tile = level.tiles.get(key)
      if (!tile) continue

      const ourArea = triangleAreaForFeature(tile.vertices, tile.indices, s.featureIndex)
      if (ourArea === 0) continue // feature absent in tile — separate concern

      const rel = Math.abs(ourArea - s.areaMercM2) / Math.max(ourArea, s.areaMercM2, 1)
      if (rel > maxRelDelta) maxRelDelta = rel
      if (rel > 0.01) {
        report.push(`${s.name} z=${s.z} x=${s.x} y=${s.y}: ours=${ourArea.toExponential(3)} shapely=${s.areaMercM2.toExponential(3)} rel=${(rel * 100).toFixed(2)}%`)
      }
    }
    // 2% tolerance: clipping snaps vertices to tile edges and earcut
    // fan-triangulates, both of which introduce O(ε²) area noise per
    // edge. Keep loose enough to absorb that but tight enough to catch
    // dropped polygons or double-counted rings.
    expect(maxRelDelta, `exceeded 2% on:\n  ${report.join('\n  ')}`).toBeLessThanOrEqual(0.02)
  })
})

// ═══ Douglas-Peucker simplification vs shapely.simplify ═══

describe('Cross-validation: Polygon simplification (vs shapely)', () => {
  // Both X-GIS and shapely use Douglas-Peucker. At the same tolerance,
  // the retained vertex set should agree for simple inputs with no
  // ties. Compare vertex count and area of the output.
  it(`matches shapely at ${fixture.simplify_samples.length} D-P cases`, () => {
    for (const s of fixture.simplify_samples) {
      const ours = xgisSimplify(s.input, s.toleranceDeg)
      // D-P is endpoint-preserving; both should keep vertices [0] and
      // [N-1]. Close the ring representation: shapely drops the dup
      // last vertex (we already stripped it in Python). X-GIS's
      // simplify also returns the open form.
      expect(ours.length,
        `${s.label} vertex count: ours=${ours.length} shapely=${s.shapelyVertexCount}`,
      ).toBe(s.shapelyVertexCount)
      // Area preservation: both simplified polygons should have very
      // similar area. D-P's theorem bounds Hausdorff distance to
      // tolerance, so area delta is ≤ perimeter × tolerance — way
      // under 1% for the chosen inputs.
      const ourArea = shoelaceArea(ours)
      expect(ourArea, `${s.label} area delta`)
        .toBeCloseTo(s.shapelyArea, 4) // 5e-5 deg² absolute
    }
  })
})

function shoelaceArea(ring: number[][]): number {
  if (ring.length < 3) return 0
  let sum = 0
  for (let i = 0; i < ring.length; i++) {
    const [x0, y0] = ring[i]
    const [x1, y1] = ring[(i + 1) % ring.length]
    sum += x0 * y1 - x1 * y0
  }
  return Math.abs(sum) * 0.5
}
