import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

import { mercator } from '../engine/projection'

// Cross-validation tests: compare our CPU math against reference values
// computed by INDEPENDENT Python libraries (pyproj, mercantile, shapely).
// The fixture is generated by scripts/cross-validation/generate-fixtures.py
// and committed to the repo. If a formula drifts from the documented
// standard, these tests catch it even when our own CPU/WGSL pair stays
// internally consistent.
//
// Why this matters: the rest of the suite verifies our CPU matches our
// WGSL. That catches intra-repo divergence but not "same bug in both".
// The Python libraries are a different codebase, different authors,
// different maintainers, and are the de-facto standards for their
// domains (GeoJSON pyproj, slippy-map mercantile, GEOS shapely).

const __dirname = dirname(fileURLToPath(import.meta.url))
const FIXTURE_PATH = resolve(__dirname, './cross-validation.fixture.json')

interface MercatorForwardSample { lon: number; lat: number; mercX: number; mercY: number }
interface MercatorInverseSample { mercX: number; mercY: number; lon: number; lat: number }
interface TileSample {
  label: string
  lon: number; lat: number; zoom: number
  tileX: number; tileY: number; tileZ: number
  boundsWest: number; boundsSouth: number; boundsEast: number; boundsNorth: number
}
interface ClipSample {
  zoom: number; tileX: number; tileY: number
  tileWest: number; tileSouth: number; tileEast: number; tileNorth: number
  tileArea: number; interArea: number; fullyCovered: boolean
}
interface Fixture {
  _meta: { generator: string; pyproj: string; mercantile: string; shapely: string }
  mercator_forward: MercatorForwardSample[]
  mercator_inverse: MercatorInverseSample[]
  tile_math: TileSample[]
  polygon_clip_contains: ClipSample[]
  constants: {
    mercator_at_zero: { lon: number; lat: number; expectedX: number; expectedY: number }
    mercator_pole_x: { lon: number; lat: number; expectedX: number; expectedY: number }
    earth_radius_m: number
    pi_times_R: number
  }
}

const fixture: Fixture = JSON.parse(readFileSync(FIXTURE_PATH, 'utf8'))

describe('Cross-validation: fixture metadata', () => {
  it('is tagged with the generator script + reference library versions', () => {
    expect(fixture._meta.generator).toBe('scripts/cross-validation/generate-fixtures.py')
    expect(fixture._meta.pyproj).toMatch(/^\d+\.\d+/)
    expect(fixture._meta.mercantile).toMatch(/^\d+\.\d+/)
    expect(fixture._meta.shapely).toMatch(/^\d+\.\d+/)
  })
})

describe('Cross-validation: Mercator forward (vs pyproj EPSG:3857)', () => {
  // Tolerance: 1 µm (1e-6 m). pyproj uses the same earth radius
  // (6378137 m per EPSG:3857 spec), so agreement should be essentially
  // perfect modulo floating-point rounding.
  const TOL_M = 1e-6
  it(`matches pyproj at ${fixture.mercator_forward.length} sample points`, () => {
    for (const s of fixture.mercator_forward) {
      const [x, y] = mercator.forward(s.lon, s.lat)
      expect(x, `lon=${s.lon}`).toBeCloseTo(s.mercX, 6) // 1 µm
      // pyproj at lat=80 returns a specific value — our clamp doesn't
      // kick in until MERCATOR_LAT_LIMIT ≈ 85.051°, so latitudes in
      // the fixture's ±80 range are projected un-clamped and should
      // match pyproj to full f64 precision.
      if (Math.abs(s.lat) < 85) {
        expect(y, `lat=${s.lat}`).toBeCloseTo(s.mercY, 6)
      }
    }
  })
})

describe('Cross-validation: Mercator inverse (vs pyproj)', () => {
  it(`recovers lon/lat from Mercator X,Y across ${fixture.mercator_inverse.length} samples`, () => {
    for (const s of fixture.mercator_inverse) {
      const [lon, lat] = mercator.inverse(s.mercX, s.mercY)
      expect(lon).toBeCloseTo(s.lon, 10)
      expect(lat).toBeCloseTo(s.lat, 10)
    }
  })
})

describe('Cross-validation: Tile math (vs mercantile)', () => {
  // mercantile uses the same (lon, lat, zoom) → tile (x, y) formula as
  // the slippy-map spec. Our loader/tiles helpers must produce the
  // same integer tile coords.
  function ourTileXY(lon: number, lat: number, zoom: number): [number, number] {
    const n = Math.pow(2, zoom)
    const x = Math.floor((lon + 180) / 360 * n)
    const clampedLat = Math.max(-85.051129, Math.min(85.051129, lat))
    const y = Math.floor(
      (1 - Math.log(Math.tan(Math.PI / 4 + clampedLat * Math.PI / 360)) / Math.PI) / 2 * n,
    )
    return [x, y]
  }

  function ourTileBounds(x: number, y: number, z: number) {
    const n = Math.pow(2, z)
    const west = x / n * 360 - 180
    const east = (x + 1) / n * 360 - 180
    const north = Math.atan(Math.sinh(Math.PI * (1 - 2 * y / n))) * 180 / Math.PI
    const south = Math.atan(Math.sinh(Math.PI * (1 - 2 * (y + 1) / n))) * 180 / Math.PI
    return { west, south, east, north }
  }

  it(`lon/lat → tile (x, y) matches mercantile at ${fixture.tile_math.length} samples`, () => {
    for (const s of fixture.tile_math) {
      // Skip polar cases at z=0: mercantile's behavior at the pole is
      // lightly undefined (one tile covers the whole world). Our
      // clamp and their clamp may differ by 1 tile; it's not a bug.
      if (s.zoom === 0 && Math.abs(s.lat) > 60) continue

      const [tx, ty] = ourTileXY(s.lon, s.lat, s.zoom)
      expect(tx, `${s.label} z=${s.zoom} x`).toBe(s.tileX)
      expect(ty, `${s.label} z=${s.zoom} y`).toBe(s.tileY)
    }
  })

  it(`tile (x, y, z) → bounds matches mercantile at ${fixture.tile_math.length} samples`, () => {
    for (const s of fixture.tile_math) {
      const b = ourTileBounds(s.tileX, s.tileY, s.tileZ)
      expect(b.west,  `${s.label} z=${s.zoom} west`).toBeCloseTo(s.boundsWest, 10)
      expect(b.east,  `${s.label} z=${s.zoom} east`).toBeCloseTo(s.boundsEast, 10)
      expect(b.south, `${s.label} z=${s.zoom} south`).toBeCloseTo(s.boundsSouth, 10)
      expect(b.north, `${s.label} z=${s.zoom} north`).toBeCloseTo(s.boundsNorth, 10)
    }
  })
})

describe('Cross-validation: Polygon full-cover (vs shapely)', () => {
  // Our full-cover detection uses an area-ratio heuristic (polygon area
  // ≈ tile area within 1e-6 relative tolerance). Shapely's `contains`
  // is the GEOS reference. When shapely says the world polygon
  // contains a tile, our fullCover detection should also trigger
  // (given the same input).
  it('shapely-contains verdict lines up with our ratio test at all zooms', () => {
    for (const s of fixture.polygon_clip_contains) {
      // Reproduce the ratio test from compileGeoJSONToTiles in lon/lat
      // space — same formula (polyArea / tileArea within 1e-6).
      const tileArea = (s.tileEast - s.tileWest) * (s.tileNorth - s.tileSouth)
      expect(tileArea).toBeCloseTo(s.tileArea, 6)
      const interArea = s.interArea
      const ourFullCover = Math.abs(interArea - tileArea) / tileArea < 1e-6
      expect(
        ourFullCover,
        `shapely says ${s.fullyCovered}, ratio says ${ourFullCover} at z=${s.zoom}`,
      ).toBe(s.fullyCovered)
    }
  })
})

describe('Cross-validation: Published EPSG:3857 reference points', () => {
  it('Mercator at origin is (0, 0)', () => {
    const [x, y] = mercator.forward(
      fixture.constants.mercator_at_zero.lon,
      fixture.constants.mercator_at_zero.lat,
    )
    // pyproj returns exact 0 at lat=0; our CPU pipeline goes through
    // Math.log(Math.tan(Math.PI/4)) × R which rounds to ~7e-10 m due
    // to tan(π/4) = 0.9999999999999999 in IEEE 754. Sub-nanometer drift
    // at the origin is expected — use µm-level tolerance.
    expect(x).toBeCloseTo(fixture.constants.mercator_at_zero.expectedX, 6)
    expect(y).toBeCloseTo(fixture.constants.mercator_at_zero.expectedY, 6)
  })

  it('Mercator X at lon=180 is π × R (≈ 20 037 508.34)', () => {
    const [x] = mercator.forward(
      fixture.constants.mercator_pole_x.lon,
      fixture.constants.mercator_pole_x.lat,
    )
    expect(x).toBeCloseTo(fixture.constants.mercator_pole_x.expectedX, 5)
    expect(fixture.constants.pi_times_R).toBe(fixture.constants.mercator_pole_x.expectedX)
    // π × 6378137 confirmed by the EPSG:3857 definition.
    expect(Math.PI * fixture.constants.earth_radius_m).toBeCloseTo(fixture.constants.pi_times_R, 6)
  })
})
