import type { CoverageEntry } from './types'

export const LAYOUT_SYMBOL: readonly CoverageEntry[] = [
  {
    name: 'symbol-placement',
    status: 'supported',
    note: 'point / line / line-center literals; `["step", ["zoom"], …]` form expands to multiple layers with intersected minzoom/maxzoom + segment-resolved placement (OFM Bright highway-shield-* coverage). Non-zoom step inputs fall back to default placement.',
    source: 'layers.ts:447',
  },
  {
    name: 'symbol-spacing',
    status: 'supported',
    note: 'Defaults to 250 px when missing on line placement.',
    source: 'layers.ts:471',
  },
  {
    name: 'symbol-avoid-edges',
    status: 'na',
    note: "na — MOOT for X-GIS' label model. Skip labels whose bbox crosses a tile boundary (de-dupe at tile seams): the tile-seam duplication this property works around does not ARISE in X-GIS, whose placement/collision runs frame-globally in screen space over cross-tile-deduped anchors, not per-tile. Faithful support is therefore not merely unimplemented but inapplicable to the architecture: the placement/collision pass (runtime text-stage.ts) operates entirely in SCREEN pixels with no tile coordinate frame (AGENTS: \"projection is the caller's responsibility\"), and the upstream label source (label-feature-source.ts forEachLabel) emits each feature as a single absolute-Mercator anchor deduped across tiles — the stride-13 point-vertex format carries ECEF + abs-lon/lat + abs-Mercator, NOT tile-local coords or the tile extent. A faithful tile-edge-crossing test needs the label's bbox in tile-local units against [0, EXTENT], which would require threading tile-local coords + extent through the VTR point-vertex format, forEachLabel, and addLabel (cross-subsystem, high blast radius). The converter RECOGNISES the property and emits a precise warning (layers-symbol.ts convertGapWarnings) noting the knob is moot for X-GIS' cross-tile-collision model. Warned, not supported.",
  },
  {
    name: 'symbol-sort-key',
    status: 'partial',
    impact: 'medium',
    note: 'Constant AND per-feature expression forms plumbed end-to-end. Constant: iter 399-405. Expression (`["get","rank"]`, match/case): converter emits `label-sort-key-[<expr>]` (#2166) → LabelDef.sortKeyExpr → applyFeatureExprs evaluates it per feature at dispatch → the collision pass sorts CollisionItems by sortKey ascending in the SAME frame (greedyPlaceBboxes), lower wins. RESIDUAL, and why this stays partial: X-GIS applies the key to COLLISION priority only. MapLibre `symbol-z-order: auto` also uses it as painter order; X-GIS draws near-first within a layer there, so two labels that overlap without colliding (an allow-overlap style) can paint in a different order. An expression resolving to a non-number falls back to the constant key, i.e. 0 — the same value the pre-#2166 drop produced.',
    source: 'layers-symbol.ts:914',
  },
  {
    name: 'symbol-z-order',
    status: 'supported',
    note: "Enum auto / viewport-y / source. Threaded end-to-end: layout `symbol-z-order` → `label-z-order-<v>` → LabelDef.symbolZOrder → TextStage.prepare() ordering pass. `viewport-y` orders labels by screen Y (lower-on-screen placed first in collision → drawn on top); `source` keeps source/feature order (suppresses the reverse-layer trick); `auto` (and unset) reproduce X-GIS' historical reverse-layer / sortKey ordering BYTE-FOR-BYTE — only an explicit `viewport-y` / `source` activates the new sort. Applied across the frame's aggregated label set (X-GIS collides all symbol layers together); per-layer-scoped viewport ordering of mutually-colliding layers is an approximation.",
    source: 'layers-symbol.ts:1079',
  },
  {
    name: 'text-field',
    status: 'supported',
    note: 'String / {token} / expression / number / boolean / null. Colon-bearing locale keys route via `get("name:xx")`.',
    source: 'layers.ts:164',
  },
  {
    name: 'text-font',
    status: 'supported',
    note: 'Family extracted, weight + italic stripped into `label-font-weight-N` / `label-italic`.',
    source: 'layers.ts:417',
  },
  {
    name: 'text-size',
    status: 'supported',
    note: 'Constant + interpolate-by-zoom + per-feature expression (sizeExpr).',
    source: 'layers.ts:231',
  },
  {
    name: 'text-max-width',
    status: 'supported',
    note: 'Constant + interpolate-by-zoom (LabelDef.maxWidth is a single em value — the authored stops fold into the utility and lower seeds the wrap width from the last one, so it does not vary per zoom); default 10 ems for non-line placement (Mapbox parity).',
    source: 'layers.ts:385',
  },
  { name: 'text-line-height', status: 'supported' },
  { name: 'text-letter-spacing', status: 'supported', note: 'Constant + interpolate-by-zoom.' },
  { name: 'text-justify', status: 'supported', note: 'auto / left / center / right literals.' },
  {
    name: 'text-anchor',
    status: 'supported',
    note: 'Full 9-way (center / top / bottom / left / right + 4 diagonals).',
    source: 'layers.ts:295',
  },
  {
    name: 'text-variable-anchor',
    status: 'supported',
    note: 'Real layout property (and legacy array-in-text-anchor) lower to anchorCandidates; runtime collision picks first non-overlapping.',
    source: 'layers.ts:370',
  },
  {
    name: 'text-variable-anchor-offset',
    status: 'supported',
    note: 'Per-anchor em offsets; runtime applies MapLibre baseline shift.',
    source: 'layers.ts:435',
  },
  {
    name: 'text-radial-offset',
    status: 'supported',
    note: 'Constant em; runtime fromRadialOffset per candidate anchor (MapLibre-parity).',
    source: 'layers.ts:435',
  },
  {
    name: 'text-offset',
    status: 'supported',
    note: 'Constant 2-tuple only.',
    source: 'layers.ts:329',
  },
  { name: 'text-rotate', status: 'supported', note: 'Constant only.' },
  {
    name: 'text-padding',
    status: 'supported',
    note: 'Constant + interpolate-by-zoom.',
    source: 'layers.ts:351',
  },
  { name: 'text-transform', status: 'supported', note: 'uppercase / lowercase / none literals.' },
  { name: 'text-allow-overlap', status: 'supported' },
  { name: 'text-ignore-placement', status: 'supported' },
  {
    name: 'text-overlap',
    status: 'partial',
    impact: 'low',
    note: 'MapLibre overlap-policy enum (never / always / cooperative). always → label-allow-overlap; never → default; cooperative approximated as always (priority-aware collision pending) + warning. Wins over legacy text-allow-overlap when both declared.',
    source: 'layers.ts:418',
  },
  {
    name: 'text-optional',
    status: 'unsupported',
    impact: 'medium',
    note: "The note this replaces read 'Icons not implemented — moot.' and both halves were false. Icons ARE implemented, and the text+icon PAIR CONTRACT is wired: a collision-rejected label adds its pairKey to TextStage's droppedPairKeys, IconStage.setDroppedPairKeys reads that ledger, and the paired icon is skipped on its next dispatch — which IS MapLibre's text+icon-as-one-symbol rule, i.e. the spec DEFAULT (`false`) is X-GIS' actual behaviour, not a gap. The real gap is `true`: letting the icon survive alone when only the label cannot fit needs SPLIT text/icon collision arbitration, which the placement queue does not have — text placement is deliberately the single authority (see icon-stage.ts's own note that icons only READ records). Impact raised low -> medium, MEASURED rather than inherited: all three shipped OpenFreeMap styles (bright / positron / liberty) author `text-optional: true` on their `airport` layer, each of which also carries an icon-image — so per the legend this is 'visible in some styles', not a rare knob. The converter warns on an explicit `true`.",
    source: 'text-stage.ts droppedPairKeys -> icon-stage.ts setDroppedPairKeys',
  },
  {
    name: 'text-rotation-alignment',
    status: 'supported',
    note: 'Literal map / viewport / auto. Honoured at runtime.',
    source: 'map.ts:2369',
  },
  {
    name: 'text-pitch-alignment',
    status: 'partial',
    impact: 'medium',
    note: 'Ground projection SHIPS, but DIAGONALLY across the label pass\'s two dispatch paths, which is why this is partial rather than supported. The path is picked by the SOURCE, before the placement is consulted: features held untiled take the raw path, tiled ones take the other. A `vector` source is always tiled, which is what a converted basemap is made of. POINT placement is ground-projected on the RAW path only — makeGroundBasisFor derives a per-label basis from the frame matrix and its pitch-0 twin and withholds it at pitch 0 (identity), so unpitched frames stay byte-identical. LINE placement is ground-projected on the TILED path only — the tangent-rotated curved branch walks a pitch-0 label plane and hands the same basis to each stop. The spec default `auto` matches text-rotation-alignment, whose own `auto` is `map` for line / line-center placement, so every `line`-placed label on a tiled source is ground-projected without authoring anything. RESIDUAL — each of these resolves to `map` and still billboards: (1) `line-center`, on either path, emits one label per feature through the non-curved fallback (emitLabelAlongSegment), which supplies no basis; (2) `line` with text-rotation-alignment `viewport` never reaches the curved branch; (3) POINT placement on a TILED source — the tiled point arms pass ten arguments to addLabel and stop before the basis parameter; (4) `line` / `line-center` on a RAW source — placeInlineLineLabels carries no basis parameter; (5) the globe projection has no map plane to lie in and is deferred by design, so a label ground-projects on the flat projections only. The converter warns on (1), (2) and (3): those are decidable from the layer alone, and groundAlignsAtRuntime models the tiled path because that is where a converted style\'s sources land. It CANNOT warn on (4) or (5) — one is a per-SOURCE fact and the other a per-FRAME one, neither visible to a per-layer predicate — so silence from the converter means "ground-projected on the tiled path", never "ground-projected on every path".',
    source: 'dispatch-point-labels.ts:116',
  },
  {
    name: 'text-keep-upright',
    status: 'supported',
    note: 'Per-glyph flip for line labels.',
    source: 'text-stage.ts:509',
  },
  {
    name: 'text-writing-mode',
    status: 'partial',
    impact: 'low',
    note: "CJK vertical point labels. Threaded end-to-end: layout `text-writing-mode` → `label-writing-mode-vertical` → LabelDef.writingMode → TextStage point loop, which lays the glyphs out as a COLUMN (`glyphOffsets` in +y at the em pitch, never at `metrics.advance`) with per-glyph `glyphRotations` of 0 for a verticalized glyph and +π/2 for one that stays horizontal — `glyphVerticalizes` is that truth table, transcribed from MapLibre's `symbol/shaping.ts` (the original is quoted in docs/plans/2026-08-24-cjk-vertical-text.md §1.2a), so Latin and digits stack UPRIGHT one per cell exactly as MapLibre draws them. Gated on the UAX#50 upright property, not on a CJK-dominance ratio: the property is a hint, and a string whose script does not support the orientation stays horizontal. PARTIAL for two reasons. (1) The array is read as a SET, not as the ordered PRIORITY list the spec documents: `vertical` present ⇒ vertical. Honouring the order needs MapLibre's per-frame horizontal/vertical arbitration (a second collision box per label), which is a separate item. (2) Vertical presentation forms for punctuation (MapLibre's punctuation verticalization, e.g. 、。「」 → the U+FE10 block) are not substituted yet, and the UAX#50 predicate is a block-range heuristic rather than the generated table. (3) Two crossings are deferred rather than half-done: an inline-image text-field keeps the HORIZONTAL pen (a column would drop its sprites), and multi-COLUMN layout is not implemented — MapLibre wraps a long vertical label into extra columns spaced by lineHeight on the cross axis, so here a hard newline consumes no cell and the label stays one column. A variable-anchor label DOES get a column per candidate; it merely stays out of the layout cache, as every variable-anchor label already does.",
    source: 'vertical-writing.ts:110',
  },
  {
    name: 'text-max-angle',
    status: 'supported',
    note: "Max degrees between adjacent glyphs on a line-placed label. Threaded end-to-end: layout `text-max-angle` → `label-max-angle-N` → LabelDef.maxAngle → TextStage curved-loop angular gate (drops the label when the wrapped per-glyph tangent delta exceeds the threshold). UNSET = the spec default of 45, which MapLibre applies to every line-placed label whether or not the style authors the property. It previously meant NO clamp, to keep unauthored styles byte-identical — but omitting it is the norm (not one of OFM Positron's five line-placed symbol layers sets it), so the gate never ran on the style parity is measured against.",
    source: 'layers-symbol.ts:1072',
  },
  {
    name: 'icon-image',
    status: 'supported',
    impact: 'high',
    note: 'Constant + data-driven match/case via label-icon-image-[<expr>] bracket binding. Per-feature evaluation in TextStage.applyFeatureExprs dispatches IconStage.addIcon. Iter 490 + 491 shipped 2026-05-18. Iter 535 verified end-to-end across the OFM Bright highway-shield path (road_N / us-interstate_N / us-state_N): the iter 531 null-comparison fix unblocks the shield-layer filter, the diagnostic quartet (iter 526/532/533/534) confirmed dispatch → vertex buffer → GPU draw all complete. The atlas ships shields as WHITE-on-transparent backgrounds (zero SDF sprites) so colored shield appearance comes from the text-field number overlay — not sprite tinting. Icon-ONLY layers (icon-image, no text-field) route the same way for a data-driven icon-image too: `["get"]` / `["match"]` / `["coalesce", ["image", …]]` no longer drop at convert (#777 I1) — the empty-text label carries iconImageExpr to the same per-feature IconStage dispatch.',
    source: 'layers.ts:1007 + map.ts:applyFeatureExprs + layer-converters/symbol.ts',
  },
  {
    name: 'icon-size',
    status: 'supported',
    note: 'Constant + zoom-interp (iter 523) + data-driven (#777 I-F). Bracket-binding `label-icon-size-[interpolate(zoom, …)]` lowers to LabelShapes.iconSize zoom-interpolated PropertyShape (runtime resolveNumberShape at dispatchIcon); `label-icon-size-[<case/match/get>]` (converter exprToXgis) lowers to a data-driven PropertyShape that applyFeatureExprs (label-pass.ts) evaluates per feature (clamped >= 0) → per-vertex quad width. OFM bright road_oneway / road_oneway_opposite (15→0.5, 19→1) honoured.',
    source: 'layers.ts:1075',
  },
  { name: 'icon-rotate', status: 'supported', note: 'Constant degrees.', source: 'layers.ts:641' },
  {
    name: 'icon-anchor',
    status: 'supported',
    note: 'Literal 9-way enum.',
    source: 'layers.ts:627',
  },
  {
    name: 'icon-offset',
    status: 'supported',
    note: '[x, y] in CSS px; split into label-icon-offset-x / -y utilities.',
    source: 'layers.ts:631',
  },
  {
    name: 'icon-allow-overlap',
    status: 'supported',
    impact: 'medium',
    note: "`true` (and absent) = X-GIS' historical always-place — OFM label_city/town/village/city_capital authoring `true` (4 layers/fixture) render unchanged. `false` now threads to the icon collision queue: layers-symbol emits `label-icon-collide` → LabelDef.iconCollide → dispatchIcon sets the IconStage `collide` AABB (#417/#419), dropping an icon whose padded box overlaps an already-placed icon. DEFAULT note: the spec default is `false`(collide), but the ABSENT default stays always-place (byte-identical to today, OFM density-safe); only an explicit `false` opts in. icon-overlap wins when both declared. Phase S Batch 4.",
    source: 'layers-symbol.ts:777 + label-pass.ts:dispatchIcon',
  },
  {
    name: 'icon-overlap',
    status: 'supported',
    impact: 'medium',
    note: 'MapLibre overlap-policy enum. `always` = X-GIS always-place default. `never` → icon collision queue (label-icon-collide → IconStage `collide` AABB). `cooperative` approximated as `never` (collide) + warning (no priority-aware icon arbitration). Wins over legacy icon-allow-overlap when both declared. Phase S Batch 4.',
    source: 'layers-symbol.ts:777 + label-pass.ts:dispatchIcon',
  },
  {
    name: 'icon-ignore-placement',
    status: 'supported',
    impact: 'medium',
    note: "`true` → the icon places AND does not block others: emits `label-icon-ignore-placement` → LabelDef.iconIgnorePlacement → dispatchIcon keeps the icon OUT of the collide queue, overriding an explicit icon-overlap:never/icon-allow-overlap:false back to always-place-and-don't-block (X-GIS' default for a non-colliding icon). `false` (default) is a no-op. Phase S Batch 4.",
    source: 'layers-symbol.ts:813 + label-pass.ts:dispatchIcon',
  },
  {
    name: 'icon-optional',
    status: 'supported',
    impact: 'low',
    note: "`true` → a colliding icon may hide while its paired text still shows: emits `label-icon-optional` → LabelDef.iconOptional. X-GIS' text is an independent TextStage symbol, so a policy-dropped icon already never cascades to its paired text — `true` is honoured. DEFAULT `false` (drop the paired text WITH the icon) needs the reverse icon→text collision signal (not wired) and is reported deferred; emitting nothing for the default keeps it byte-identical. Phase S Batch 4.",
    source: 'layers-symbol.ts:862',
  },
  {
    name: 'icon-rotation-alignment',
    status: 'supported',
    impact: 'medium',
    note: 'All three values (map / viewport / auto) honored. "viewport"/"auto" map to X-GIS axis-aligned icons; "map" adds the per-segment tangent to icon-rotate at dispatch time under symbol-placement=line (OFM road_oneway one-way arrows). Compiler iter 506 emits label-icon-rotation-alignment-map; runtime adds tangent in dispatchIcon.',
    source: 'layers.ts:1056 + map.ts:dispatchIcon',
  },
  {
    name: 'icon-padding',
    status: 'supported',
    impact: 'low',
    note: 'Per-icon collision-bbox padding (layout, px, default 2). Constant form lowered (#777 I-D): converter emits label-icon-padding-N for non-default values only → LabelDef.iconPadding → dispatchIcon → IconStage collision box replaces the fixed 2*dpr. Non-constant (zoom-interp / data-driven) forms deferred; data-driven → cluster I-F.',
  },
  {
    name: 'icon-text-fit',
    status: 'supported',
    impact: 'medium',
    note: "Shield/badge backgrounds: the icon sprite quad stretches to wrap the PAIRED label's shaped text bbox. Constant enum lowered (#777 I-A): converter emits label-icon-text-fit-<width|height|both> → LabelDef.iconTextFit → label-pass dispatchIcon passes the fit to IconStage → IconStage.prepare reads the paired text bbox TextStage laid out this frame (pairKey → getPairFitBoxes) → icon-renderer stretches drawW/drawH before anchorOffset. `none`/absent = native sprite size (byte-identical). Non-constant (expression) forms warn once.",
  },
  {
    name: 'icon-text-fit-padding',
    status: 'supported',
    impact: 'low',
    note: 'Per-side [top,right,bottom,left] padding on the fitted quad, dependent on icon-text-fit (#777 I-A). Converter emits per-side label-icon-text-fit-padding-{t,r,b,l}-N (only inside the fit branch; a zero side / default [0,0,0,0] emits nothing → byte-identical) → LabelDef.iconTextFitPadding → IconStage adds it (× dpr) to the fitted dims and shifts the quad centre for asymmetric padding. Negatives clamp to 0 with a warning.',
  },
  {
    name: 'icon-keep-upright',
    status: 'supported',
    impact: 'low',
    note: "Flip line-placed icons so they face up (icon twin of text-keep-upright). Constant form lowered (#777 I-B): converter emits label-icon-keep-upright / label-icon-keep-upright-false → LabelDef.iconKeepUpright → label-pass dispatchIcon folds a downward segment tangent into the upright half-plane (resolveIconRotateRad) under symbol-placement=line + icon-rotation-alignment=map. DEFAULT: Mapbox's spec default is `false` and X-GIS's ABSENT behaviour already matches it — always-follow-tangent, no fold. The fold activates ONLY on an EXPLICITLY authored value. Non-constant (zoom-interp / data-driven) forms warn and skip.",
  },
  {
    name: 'icon-pitch-alignment',
    status: 'unsupported',
    impact: 'low',
    note: 'map / viewport / auto — the spec default is `auto`, NOT viewport. X-GIS uses viewport-aligned icons unconditionally; map mode would project the icon quad onto the ground plane.',
  },
]
