import type { CoverageEntry } from './types'

export const LAYOUT_SYMBOL: readonly CoverageEntry[] = [
  {
    name: 'symbol-placement',
    status: 'supported',
    note: 'point / line / line-center literals; `["step", ["zoom"], …]` form expands to multiple layers with intersected minzoom/maxzoom + segment-resolved placement (OFM Bright highway-shield-* coverage). Non-zoom step inputs fall back to default placement.',
    source: 'layers.ts:447',
  },
  {
    name: 'symbol-spacing',
    status: 'supported',
    note: 'Defaults to 250 px when missing on line placement.',
    source: 'layers.ts:471',
  },
  {
    name: 'symbol-avoid-edges',
    status: 'na',
    note: "na — MOOT for X-GIS' label model. Skip labels whose bbox crosses a tile boundary (de-dupe at tile seams): the tile-seam duplication this property works around does not ARISE in X-GIS, whose placement/collision runs frame-globally in screen space over cross-tile-deduped anchors, not per-tile. Faithful support is therefore not merely unimplemented but inapplicable to the architecture: the placement/collision pass (runtime text-stage.ts) operates entirely in SCREEN pixels with no tile coordinate frame (AGENTS: \"projection is the caller's responsibility\"), and the upstream label source (label-feature-source.ts forEachLabel) emits each feature as a single absolute-Mercator anchor deduped across tiles — the stride-13 point-vertex format carries ECEF + abs-lon/lat + abs-Mercator, NOT tile-local coords or the tile extent. A faithful tile-edge-crossing test needs the label's bbox in tile-local units against [0, EXTENT], which would require threading tile-local coords + extent through the VTR point-vertex format, forEachLabel, and addLabel (cross-subsystem, high blast radius). The converter RECOGNISES the property and emits a precise warning (layers-symbol.ts convertGapWarnings) noting the knob is moot for X-GIS' cross-tile-collision model. Warned, not supported.",
  },
  {
    name: 'symbol-sort-key',
    status: 'partial',
    impact: 'medium',
    note: 'Constant numeric value plumbed end-to-end (iter 399-405). Runtime collision pass sorts CollisionItems by sortKey ascending — lower wins. Expression form (`["get", "rank"]`) flattens to 0 with a warning.',
    source: 'layers.ts:702',
  },
  {
    name: 'symbol-z-order',
    status: 'supported',
    note: "Enum auto / viewport-y / source. Threaded end-to-end: layout `symbol-z-order` → `label-z-order-<v>` → LabelDef.symbolZOrder → TextStage.prepare() ordering pass. `viewport-y` orders labels by screen Y (lower-on-screen placed first in collision → drawn on top); `source` keeps source/feature order (suppresses the reverse-layer trick); `auto` (and unset) reproduce X-GIS' historical reverse-layer / sortKey ordering BYTE-FOR-BYTE — only an explicit `viewport-y` / `source` activates the new sort. Applied across the frame's aggregated label set (X-GIS collides all symbol layers together); per-layer-scoped viewport ordering of mutually-colliding layers is an approximation.",
    source: 'layers-symbol.ts:1079',
  },
  {
    name: 'text-field',
    status: 'supported',
    note: 'String / {token} / expression / number / boolean / null. Colon-bearing locale keys route via `get("name:xx")`.',
    source: 'layers.ts:164',
  },
  {
    name: 'text-font',
    status: 'supported',
    note: 'Family extracted, weight + italic stripped into `label-font-weight-N` / `label-italic`.',
    source: 'layers.ts:417',
  },
  {
    name: 'text-size',
    status: 'supported',
    note: 'Constant + interpolate-by-zoom + per-feature expression (sizeExpr).',
    source: 'layers.ts:231',
  },
  {
    name: 'text-max-width',
    status: 'supported',
    note: 'Default 10 ems for non-line placement (Mapbox parity).',
    source: 'layers.ts:385',
  },
  { name: 'text-line-height', status: 'supported' },
  { name: 'text-letter-spacing', status: 'supported', note: 'Constant + interpolate-by-zoom.' },
  { name: 'text-justify', status: 'supported', note: 'auto / left / center / right literals.' },
  {
    name: 'text-anchor',
    status: 'supported',
    note: 'Full 9-way (center / top / bottom / left / right + 4 diagonals).',
    source: 'layers.ts:295',
  },
  {
    name: 'text-variable-anchor',
    status: 'supported',
    note: 'Real layout property (and legacy array-in-text-anchor) lower to anchorCandidates; runtime collision picks first non-overlapping.',
    source: 'layers.ts:370',
  },
  {
    name: 'text-variable-anchor-offset',
    status: 'supported',
    note: 'Per-anchor em offsets; runtime applies MapLibre baseline shift.',
    source: 'layers.ts:435',
  },
  {
    name: 'text-radial-offset',
    status: 'supported',
    note: 'Constant em; runtime fromRadialOffset per candidate anchor (MapLibre-parity).',
    source: 'layers.ts:435',
  },
  {
    name: 'text-offset',
    status: 'supported',
    note: 'Constant 2-tuple only.',
    source: 'layers.ts:329',
  },
  { name: 'text-rotate', status: 'supported', note: 'Constant only.' },
  {
    name: 'text-padding',
    status: 'supported',
    note: 'Constant + interpolate-by-zoom.',
    source: 'layers.ts:351',
  },
  { name: 'text-transform', status: 'supported', note: 'uppercase / lowercase / none literals.' },
  { name: 'text-allow-overlap', status: 'supported' },
  { name: 'text-ignore-placement', status: 'supported' },
  {
    name: 'text-overlap',
    status: 'partial',
    impact: 'low',
    note: 'MapLibre overlap-policy enum (never / always / cooperative). always → label-allow-overlap; never → default; cooperative approximated as always (priority-aware collision pending) + warning. Wins over legacy text-allow-overlap when both declared.',
    source: 'layers.ts:418',
  },
  {
    name: 'text-optional',
    status: 'unsupported',
    impact: 'low',
    note: 'Icons not implemented — moot.',
  },
  {
    name: 'text-rotation-alignment',
    status: 'supported',
    note: 'Literal map / viewport / auto. Honoured at runtime.',
    source: 'map.ts:2369',
  },
  {
    name: 'text-pitch-alignment',
    status: 'partial',
    impact: 'medium',
    note: "Converter emits, runtime ignores — labels never project onto ground plane. Iter 10 surfaced an explicit warning when `map` is authored (the gap-revealing case) so authors of pitched-view styles see the diagnostic. `viewport` and `auto` match X-GIS' billboard-rendering default and stay silent.",
    source: 'map.ts:2461',
  },
  {
    name: 'text-keep-upright',
    status: 'supported',
    note: 'Per-glyph flip for line labels.',
    source: 'text-stage.ts:509',
  },
  {
    name: 'text-writing-mode',
    status: 'unsupported',
    impact: 'medium',
    note: 'CJK vertical text would need a per-glyph rotation pipeline.',
  },
  {
    name: 'text-max-angle',
    status: 'supported',
    note: "Max degrees between adjacent glyphs on a line-placed label. Threaded end-to-end: layout `text-max-angle` → `label-max-angle-N` → LabelDef.maxAngle → TextStage curved-loop angular gate (drops the label when the wrapped per-glyph tangent delta exceeds the threshold). UNSET = no clamp (X-GIS historical behaviour preserved byte-for-byte for styles that don't author it); authoring a value (incl. spec default 45) activates the gate.",
    source: 'layers-symbol.ts:1072',
  },
  {
    name: 'icon-image',
    status: 'supported',
    impact: 'high',
    note: 'Constant + data-driven match/case via label-icon-image-[<expr>] bracket binding. Per-feature evaluation in TextStage.applyFeatureExprs dispatches IconStage.addIcon. Iter 490 + 491 shipped 2026-05-18. Iter 535 verified end-to-end across the OFM Bright highway-shield path (road_N / us-interstate_N / us-state_N): the iter 531 null-comparison fix unblocks the shield-layer filter, the diagnostic quartet (iter 526/532/533/534) confirmed dispatch → vertex buffer → GPU draw all complete. The atlas ships shields as WHITE-on-transparent backgrounds (zero SDF sprites) so colored shield appearance comes from the text-field number overlay — not sprite tinting. Icon-ONLY layers (icon-image, no text-field) route the same way for a data-driven icon-image too: `["get"]` / `["match"]` / `["coalesce", ["image", …]]` no longer drop at convert (#777 I1) — the empty-text label carries iconImageExpr to the same per-feature IconStage dispatch.',
    source: 'layers.ts:1007 + map.ts:applyFeatureExprs + layer-converters/symbol.ts',
  },
  {
    name: 'icon-size',
    status: 'supported',
    note: 'Constant + zoom-interp (iter 523) + data-driven (#777 I-F). Bracket-binding `label-icon-size-[interpolate(zoom, …)]` lowers to LabelShapes.iconSize zoom-interpolated PropertyShape (runtime resolveNumberShape at dispatchIcon); `label-icon-size-[<case/match/get>]` (converter exprToXgis) lowers to a data-driven PropertyShape that applyFeatureExprs (label-pass.ts) evaluates per feature (clamped >= 0) → per-vertex quad width. OFM bright road_oneway / road_oneway_opposite (15→0.5, 19→1) honoured.',
    source: 'layers.ts:1075',
  },
  { name: 'icon-rotate', status: 'supported', note: 'Constant degrees.', source: 'layers.ts:641' },
  {
    name: 'icon-anchor',
    status: 'supported',
    note: 'Literal 9-way enum.',
    source: 'layers.ts:627',
  },
  {
    name: 'icon-offset',
    status: 'supported',
    note: '[x, y] in CSS px; split into label-icon-offset-x / -y utilities.',
    source: 'layers.ts:631',
  },
  {
    name: 'icon-allow-overlap',
    status: 'supported',
    impact: 'medium',
    note: "`true` (and absent) = X-GIS' historical always-place — OFM label_city/town/village/city_capital authoring `true` (4 layers/fixture) render unchanged. `false` now threads to the icon collision queue: layers-symbol emits `label-icon-collide` → LabelDef.iconCollide → dispatchIcon sets the IconStage `collide` AABB (#417/#419), dropping an icon whose padded box overlaps an already-placed icon. DEFAULT note: the spec default is `false`(collide), but the ABSENT default stays always-place (byte-identical to today, OFM density-safe); only an explicit `false` opts in. icon-overlap wins when both declared. Phase S Batch 4.",
    source: 'layers-symbol.ts:777 + label-pass.ts:dispatchIcon',
  },
  {
    name: 'icon-overlap',
    status: 'supported',
    impact: 'medium',
    note: 'MapLibre overlap-policy enum. `always` = X-GIS always-place default. `never` → icon collision queue (label-icon-collide → IconStage `collide` AABB). `cooperative` approximated as `never` (collide) + warning (no priority-aware icon arbitration). Wins over legacy icon-allow-overlap when both declared. Phase S Batch 4.',
    source: 'layers-symbol.ts:777 + label-pass.ts:dispatchIcon',
  },
  {
    name: 'icon-ignore-placement',
    status: 'supported',
    impact: 'medium',
    note: "`true` → the icon places AND does not block others: emits `label-icon-ignore-placement` → LabelDef.iconIgnorePlacement → dispatchIcon keeps the icon OUT of the collide queue, overriding an explicit icon-overlap:never/icon-allow-overlap:false back to always-place-and-don't-block (X-GIS' default for a non-colliding icon). `false` (default) is a no-op. Phase S Batch 4.",
    source: 'layers-symbol.ts:813 + label-pass.ts:dispatchIcon',
  },
  {
    name: 'icon-optional',
    status: 'supported',
    impact: 'low',
    note: "`true` → a colliding icon may hide while its paired text still shows: emits `label-icon-optional` → LabelDef.iconOptional. X-GIS' text is an independent TextStage symbol, so a policy-dropped icon already never cascades to its paired text — `true` is honoured. DEFAULT `false` (drop the paired text WITH the icon) needs the reverse icon→text collision signal (not wired) and is reported deferred; emitting nothing for the default keeps it byte-identical. Phase S Batch 4.",
    source: 'layers-symbol.ts:862',
  },
  {
    name: 'icon-rotation-alignment',
    status: 'supported',
    impact: 'medium',
    note: 'All three values (map / viewport / auto) honored. "viewport"/"auto" map to X-GIS axis-aligned icons; "map" adds the per-segment tangent to icon-rotate at dispatch time under symbol-placement=line (OFM road_oneway one-way arrows). Compiler iter 506 emits label-icon-rotation-alignment-map; runtime adds tangent in dispatchIcon.',
    source: 'layers.ts:1056 + map.ts:dispatchIcon',
  },
  {
    name: 'icon-padding',
    status: 'supported',
    impact: 'low',
    note: 'Per-icon collision-bbox padding (layout, px, default 2). Constant form lowered (#777 I-D): converter emits label-icon-padding-N for non-default values only → LabelDef.iconPadding → dispatchIcon → IconStage collision box replaces the fixed 2*dpr. Non-constant (zoom-interp / data-driven) forms deferred; data-driven → cluster I-F.',
  },
  {
    name: 'icon-text-fit',
    status: 'unsupported',
    impact: 'medium',
    note: 'Shield/badge backgrounds depend on this.',
  },
  {
    name: 'icon-text-fit-padding',
    status: 'unsupported',
    impact: 'low',
    note: 'Padding when icon-text-fit fits glyph bbox; dependent on icon-text-fit.',
  },
  {
    name: 'icon-keep-upright',
    status: 'supported',
    impact: 'low',
    note: "Flip line-placed icons so they face up (icon twin of text-keep-upright). Constant form lowered (#777 I-B): converter emits label-icon-keep-upright / label-icon-keep-upright-false → LabelDef.iconKeepUpright → label-pass dispatchIcon folds a downward segment tangent into the upright half-plane (resolveIconRotateRad) under symbol-placement=line + icon-rotation-alignment=map. DEFAULT: Mapbox's spec default is `true`, but X-GIS activates the fold ONLY on an EXPLICITLY authored value — an ABSENT property keeps today's always-follow-tangent render byte-identical (icon-allow-overlap absent-default precedent); flipping the absent-default requires its own §5 before/after sweep. Non-constant (zoom-interp / data-driven) forms warn and skip.",
  },
  {
    name: 'icon-pitch-alignment',
    status: 'unsupported',
    impact: 'low',
    note: 'viewport (default) / map / auto. X-GIS uses viewport-aligned icons unconditionally; map mode would project the icon quad onto the ground plane.',
  },
]
