import type { CoverageEntry } from './types'

export const LAYOUT_SYMBOL: readonly CoverageEntry[] = [
  { name: 'symbol-placement',     status: 'supported', note: 'point / line / line-center literals; `["step", ["zoom"], …]` form expands to multiple layers with intersected minzoom/maxzoom + segment-resolved placement (OFM Bright highway-shield-* coverage). Non-zoom step inputs fall back to default placement.', source: 'layers.ts:447' },
  { name: 'symbol-spacing',       status: 'supported', note: 'Defaults to 250 px when missing on line placement.', source: 'layers.ts:471' },
  { name: 'symbol-avoid-edges',   status: 'unsupported', impact: 'low', note: 'Skip labels whose bbox crosses tile boundaries. Useful for de-duping labels at tile seams; X-GIS today uses cross-tile collision instead.' },
  { name: 'symbol-sort-key',      status: 'partial', impact: 'medium', note: 'Constant numeric value plumbed end-to-end (iter 399-405). Runtime collision pass sorts CollisionItems by sortKey ascending — lower wins. Expression form (`["get", "rank"]`) flattens to 0 with a warning.', source: 'layers.ts:702' },
  { name: 'symbol-z-order',       status: 'unsupported', impact: 'low', note: 'Per-feature draw-order override. X-GIS uses symbol-sort-key for ordering today; symbol-z-order would need a separate sort pass after collision.' },
  { name: 'text-field',           status: 'supported', note: 'String / {token} / expression / number / boolean / null. Colon-bearing locale keys route via `get("name:xx")`.', source: 'layers.ts:164' },
  { name: 'text-font',            status: 'supported', note: 'Family extracted, weight + italic stripped into `label-font-weight-N` / `label-italic`.', source: 'layers.ts:417' },
  { name: 'text-size',            status: 'supported', note: 'Constant + interpolate-by-zoom + per-feature expression (sizeExpr).', source: 'layers.ts:231' },
  { name: 'text-max-width',       status: 'supported', note: 'Default 10 ems for non-line placement (Mapbox parity).', source: 'layers.ts:385' },
  { name: 'text-line-height',     status: 'supported' },
  { name: 'text-letter-spacing',  status: 'supported', note: 'Constant + interpolate-by-zoom.' },
  { name: 'text-justify',         status: 'supported', note: 'auto / left / center / right literals.' },
  { name: 'text-anchor',          status: 'supported', note: 'Full 9-way (center / top / bottom / left / right + 4 diagonals).', source: 'layers.ts:295' },
  { name: 'text-variable-anchor', status: 'supported', note: 'Real layout property (and legacy array-in-text-anchor) lower to anchorCandidates; runtime collision picks first non-overlapping.', source: 'layers.ts:370' },
  { name: 'text-variable-anchor-offset', status: 'supported', note: 'Per-anchor em offsets; runtime applies MapLibre baseline shift.', source: 'layers.ts:435' },
  { name: 'text-radial-offset',   status: 'supported', note: 'Constant em; runtime fromRadialOffset per candidate anchor (MapLibre-parity).', source: 'layers.ts:435' },
  { name: 'text-offset',          status: 'supported', note: 'Constant 2-tuple only.', source: 'layers.ts:329' },
  { name: 'text-rotate',          status: 'supported', note: 'Constant only.' },
  { name: 'text-padding',         status: 'supported', note: 'Constant + interpolate-by-zoom.', source: 'layers.ts:351' },
  { name: 'text-transform',       status: 'supported', note: 'uppercase / lowercase / none literals.' },
  { name: 'text-allow-overlap',   status: 'supported' },
  { name: 'text-ignore-placement',status: 'supported' },
  { name: 'text-overlap',         status: 'partial', impact: 'low', note: 'MapLibre overlap-policy enum (never / always / cooperative). always → label-allow-overlap; never → default; cooperative approximated as always (priority-aware collision pending) + warning. Wins over legacy text-allow-overlap when both declared.', source: 'layers.ts:418' },
  { name: 'text-optional',        status: 'unsupported', impact: 'low', note: 'Icons not implemented — moot.' },
  { name: 'text-rotation-alignment', status: 'supported', note: 'Literal map / viewport / auto. Honoured at runtime.', source: 'map.ts:2369' },
  { name: 'text-pitch-alignment', status: 'partial', impact: 'medium', note: 'Converter emits, runtime ignores — labels never project onto ground plane. Iter 10 surfaced an explicit warning when `map` is authored (the gap-revealing case) so authors of pitched-view styles see the diagnostic. `viewport` and `auto` match X-GIS\' billboard-rendering default and stay silent.', source: 'map.ts:2461' },
  { name: 'text-keep-upright',    status: 'supported', note: 'Per-glyph flip for line labels.', source: 'text-stage.ts:509' },
  { name: 'text-writing-mode',    status: 'unsupported', impact: 'medium', note: 'CJK vertical text would need a per-glyph rotation pipeline.' },
  { name: 'text-max-angle',       status: 'unsupported', impact: 'low', note: 'Maximum angle between consecutive glyphs on a line-placed label. X-GIS uses a fixed threshold; per-layer override would thread through label-placement.' },
  { name: 'icon-image',           status: 'supported', impact: 'high', note: 'Constant + data-driven match/case via label-icon-image-[<expr>] bracket binding. Per-feature evaluation in TextStage.applyFeatureExprs dispatches IconStage.addIcon. Iter 490 + 491 shipped 2026-05-18. Iter 535 verified end-to-end across the OFM Bright highway-shield path (road_N / us-interstate_N / us-state_N): the iter 531 null-comparison fix unblocks the shield-layer filter, the diagnostic quartet (iter 526/532/533/534) confirmed dispatch → vertex buffer → GPU draw all complete. The atlas ships shields as WHITE-on-transparent backgrounds (zero SDF sprites) so colored shield appearance comes from the text-field number overlay — not sprite tinting.', source: 'layers.ts:1007 + map.ts:applyFeatureExprs' },
  { name: 'icon-size',            status: 'supported', note: 'Constant + zoom-interp (iter 523). Bracket-binding `label-icon-size-[interpolate(zoom, …)]` lowers to LabelShapes.iconSize PropertyShape; runtime resolveNumberShape at dispatchIcon time. Data-driven (case/match/get) still drops with a warning — no per-feature path. OFM bright road_oneway / road_oneway_opposite (15→0.5, 19→1) honoured.', source: 'layers.ts:1075' },
  { name: 'icon-rotate',          status: 'supported', note: 'Constant degrees.', source: 'layers.ts:641' },
  { name: 'icon-anchor',          status: 'supported', note: 'Literal 9-way enum.', source: 'layers.ts:627' },
  { name: 'icon-offset',          status: 'supported', note: '[x, y] in CSS px; split into label-icon-offset-x / -y utilities.', source: 'layers.ts:631' },
  { name: 'icon-allow-overlap',   status: 'partial', impact: 'medium', note: 'No icon collision queue yet — every icon places (matches `true` semantics). OFM label_city/town/village/city_capital authoring `true` (4 layers per fixture) renders correctly. `false` would suppress overlapping icons; not implemented (would need icon-side collision bboxes). Iter 495 status review.' },
  { name: 'icon-overlap',         status: 'partial', impact: 'medium', note: 'MapLibre overlap-policy enum. `always` matches X-GIS default (every icon places). `never`/`cooperative` need icon collision bboxes (deferred). Iter 495 status review.' },
  { name: 'icon-ignore-placement',status: 'unsupported', impact: 'medium', note: 'Same icon-collision gap as icon-allow-overlap. "true" would let other labels overlap this icon\'s footprint.' },
  { name: 'icon-optional',        status: 'partial', impact: 'low', note: 'Default `false` (icon required for label placement) is X-GIS\' current contract — labels with iconImage place when both fit. OFM label_city/town/etc. all author the default. `true` (label may place icon-less) needs icon-side collision arbitration; not implemented.' },
  { name: 'icon-rotation-alignment', status: 'supported', impact: 'medium', note: 'All three values (map / viewport / auto) honored. "viewport"/"auto" map to X-GIS axis-aligned icons; "map" adds the per-segment tangent to icon-rotate at dispatch time under symbol-placement=line (OFM road_oneway one-way arrows). Compiler iter 506 emits label-icon-rotation-alignment-map; runtime adds tangent in dispatchIcon.', source: 'layers.ts:1056 + map.ts:dispatchIcon' },
  { name: 'icon-padding',         status: 'unsupported', impact: 'low', note: 'Per-icon collision-bbox padding. X-GIS uses a fixed 2px default per spec; per-layer override needs to thread through label-collision.' },
  { name: 'icon-text-fit',        status: 'unsupported', impact: 'medium', note: 'Shield/badge backgrounds depend on this.' },
  { name: 'icon-text-fit-padding',status: 'unsupported', impact: 'low', note: 'Padding when icon-text-fit fits glyph bbox; dependent on icon-text-fit.' },
  { name: 'icon-keep-upright',    status: 'unsupported', impact: 'low', note: 'Flip line-placed icons so they always face up. Currently icons follow the symbol-placement=line tangent without flipping.' },
  { name: 'icon-pitch-alignment', status: 'unsupported', impact: 'low', note: 'viewport (default) / map / auto. X-GIS uses viewport-aligned icons unconditionally; map mode would project the icon quad onto the ground plane.' },
]
