import type { CoverageEntry } from './types'

export const PAINT_SYMBOL: readonly CoverageEntry[] = [
  { name: 'text-color',       status: 'supported', note: 'Constant + interpolate-by-zoom + per-feature colorExpr.', source: 'layers.ts:199' },
  { name: 'text-opacity',     status: 'supported', note: 'Constant folded into label-color alpha (applyAlphaMultiplier). Zoom-interp + data-driven emit `label-opacity-[…]` → LabelShapes.opacity PropertyShape; runtime resolveNumberShape multiplies into resolvedColor.a + resolvedHalo.color.a per frame. Iter 113.', source: 'layers.ts:480' },
  { name: 'text-halo-color',  status: 'supported', note: 'Constant + interpolate-by-zoom.', source: 'layers.ts:269' },
  { name: 'text-halo-width',  status: 'supported', note: 'Constant + interpolate-by-zoom; PR #76 fixed scaling into SDF units.', source: 'layers.ts:259' },
  { name: 'text-halo-blur',   status: 'supported', note: 'Constant only at conversion; IR exposes a PropertyShape so future zoom-interp / data-driven emit lands without IR changes.', source: 'layers.ts:283' },
  { name: 'text-translate',   status: 'supported', note: 'Pixel-space offset added on top of em-unit text-offset.', source: 'layers.ts:340' },
  { name: 'text-translate-anchor', status: 'unsupported', impact: 'low', note: 'viewport (default) vs map coordinate space for text-translate. X-GIS applies text-translate in viewport space only; the `map` mode would need MVP-aware offset.' },
  { name: 'icon-color',       status: 'supported', note: 'SDF sprite tint. iter 138 (Plan §4): IconRenderer carries a per-vertex tint + fwidth SDF fragment path; one batch mixes raster + SDF quads (per-vertex sdf flag, no pipeline split). Constant + zoom-interp + data-driven all route through LabelShapes.iconColor PropertyShape<RGBA> (same contract as text-color); runtime resolveColorShape at dispatchIcon → IconStage tint. Raster sprites ignore the tint per Mapbox spec.', source: 'layers.ts icon-color emit / icon-renderer.ts fs sdf branch' },
  { name: 'icon-opacity',     status: 'supported', note: 'Constant + zoom-interp + data-driven all route through LabelShapes.iconOpacity PropertyShape. Runtime resolveNumberShape at dispatchIcon → IconStage.addIcon per-vertex alpha. Iter 113.', source: 'layers.ts:1260' },
  { name: 'icon-halo-color',  status: 'unsupported', impact: 'low', note: 'SDF icon halo colour. iter-162 probe (playground/scripts/sprite-sdf-buffer-probe.ts) fetched the live OFM bright sprite: 264 entries, ZERO SDF. icon-halo applies ONLY to SDF sprites (Mapbox spec), so for the dominant OFM target styles this property is a NO-OP — implementing the composite produces zero visual change there. impact reclassified medium → low. iter-138 SDF icon foundation (fragment branch + per-vertex tint) STAYS and correctly serves any future style with SDF icons (USA OSM highway-shield-heavy styles, custom sprites). Composite shader work (second smoothstep at edge-haloWidth, mirror fs_text) is straightforward; the spritezero buffer constant remains UNRESOLVED (pin via the probe when a style with SDF icons becomes the target).' },
  { name: 'icon-halo-width',  status: 'unsupported', impact: 'low', note: 'SDF icon halo width. Same iter-162 disposition as icon-halo-color: OFM bright has 0 SDF icons → no-op on the target style. impact reclassified medium → low.' },
  { name: 'icon-halo-blur',   status: 'unsupported', impact: 'low', note: 'SDF icon halo feather. Same iter-162 disposition: OFM bright has 0 SDF icons → no-op on the target style.' },
  { name: 'icon-translate',   status: 'partial', impact: 'low', note: 'CSS-px viewport offset for icons (independent of text-translate). Constant [dx, dy] form wired end-to-end: converter emits `label-icon-translate-{x,y}-N` (layers-symbol.ts) → LabelDef.iconTranslateX/Y → dispatchIcon adds it (× dpr) to the icon anchor before IconStage.addIcon (label-pass.ts), alongside icon-offset. Default [0,0] = no-op. Non-constant (expression / interpolate) form still warns + drops.', source: 'layers-symbol.ts icon-translate emit / label-pass.ts dispatchIcon' },
  { name: 'icon-translate-anchor', status: 'partial', impact: 'low', note: 'Only `viewport` (the value matching X-GIS\' screen-space icon-translate) is honoured. `map` (world-space offset on bearing) warns + is not implemented.', source: 'layers-symbol.ts icon-translate-anchor' },
]
