import type { CoverageEntry } from './types'

export const PAINT_CIRCLE: readonly CoverageEntry[] = [
  { name: 'circle-radius',       status: 'supported', note: 'Constant + interpolate-by-zoom + per-feature expression. CSS px (Mapbox radius = xgis size).', source: 'layers.ts:537' },
  { name: 'circle-color',        status: 'supported', note: 'Constant + interpolate-by-zoom + per-feature case/match.' },
  { name: 'circle-opacity',      status: 'supported', note: 'Mapbox 0..1 → xgis 0..100 scaled. Constant + interpolate-by-zoom.' },
  { name: 'circle-stroke-color', status: 'supported' },
  { name: 'circle-stroke-width', status: 'supported', note: 'CSS px; constant + interpolate-by-zoom.' },
  { name: 'circle-blur',         status: 'partial', impact: 'low', note: 'Constant numeric form extends the point fragment smoothstep AA band via circle_params.z in the point uniform (layers-circle.ts). Zoom-interp / data-driven forms warn + drop — need a per-feature feat_data slot for per-feature blur.', source: 'layers-circle.ts:circle-blur block' },
  { name: 'circle-stroke-opacity', status: 'supported', impact: 'low', note: 'Constant numeric form folds into stroke-color hex alpha at compile time (iter 4). Zoom-interp form (WS-1, part 4) emits a stroke-opacity-[interpolate(zoom, …)] binding that lower.ts threads to ShowCommand.circleStrokeOpacityShape; PointRenderer.updateDynamicSizes resolves it per frame (resolveNumberShape) and multiplies the alpha into the circle\'s baked stroke alpha (feat_data slot 8). Non-interpolate data-driven forms still warn + drop.', source: 'layers-circle.ts:circle-stroke block' },
  { name: 'circle-translate',    status: 'supported', impact: 'low', note: 'Constant [dx, dy] vec2 AND per-frame zoom-interp now wired end-to-end through the point frame uniform (circle_params.xy — uf 32/33). The constant form emits circle-translate-x-N / circle-translate-y-M; the zoom-interp form splits the vec2 per-axis into circle-translate-{x,y}-[interpolate(zoom, …)] bindings (mirrors addFillTranslate). lower.ts threads both the constant ShowCommand.circleTranslateX/Y and the circleTranslate{X,Y}Shape; PointRenderer.updateDynamicSizes resolves the shapes each frame (resolveNumberShape) into the layer translate the uniform bakes to NDC-per-pixel. This also closed the prior gap where the GeoJSON point addLayer path (map.ts) never threaded circle-translate at all. circle-translate-anchor:map stays deferred (WS-4a).', source: 'layers-circle.ts:circle-translate block' },
  { name: 'circle-translate-anchor', status: 'partial', impact: 'low', note: "viewport (spec default) is the only honoured mode — X-GIS point renderer always applies the translate in viewport/NDC space. 'map'-anchor (world-space shift) is unsupported and warns + drops. The anchor no-op suppression (when circle-translate is absent) mirrors fill-translate-anchor behaviour.", source: 'layers-circle.ts:circle-translate-anchor block' },
  { name: 'circle-pitch-scale',  status: 'supported', impact: 'low', note: "viewport (spec default — radius constant in screen px, byte-identical) AND map. The converter emits a circle-pitch-scale-map flag only for 'map'; lower threads it through RenderNode/ShowCommand.circlePitchScaleMap → PointRenderer packs it into the point uniform circle_params.w, and the point VS scales the screen radius by w_ref/clip.w (w_ref = mvp[3][3]) so circles foreshorten with pitch/distance — mirrors MapLibre circle.vertex.glsl's pitch-scale:map for the viewport-aligned path.", source: 'layers-circle.ts:circle-pitch-scale block' },
  { name: 'circle-pitch-alignment', status: 'unsupported', impact: 'low', note: "viewport (spec default — billboard, byte-identical) vs map. X-GIS uses viewport-aligned (camera-facing) circles; 'map' mode (disc lies flat on the ground plane, tilts/foreshortens with pitch) needs a per-projection ground-tangent quad expansion across the flat-Merc / ECEF / globe vertex spaces and is deferred. 'map' still warns + drops." },
]
