// ═══ Baked shaders — artifact assembly (the logic map/scripts/bake-shaders.ts drives) ═══
//
// The generator is a thin driver by design: `map/scripts/` is OUTSIDE map's tsconfig
// `include` (rootDir is `src`), so anything living there is invisible to `tsc --build`
// — the repo's typecheck authority. Everything that can be wrong therefore lives here,
// under map/src, where the build checks it and the sync gate can import it: the key
// walk, the dedup, and the exact text of the emitted modules. The script only
// configures the host seams, calls these two functions, and writes + formats files.

import {
  BAKED_SHADER_KEYS,
  bakedContentHash,
  currentBakedMeta,
  type BakedArtifact,
  type BakedGroup,
  type BakedLanguage,
} from './registry'

/** The two axes an artifact FILE is keyed on. Language, because a device reads exactly
 *  one; group, because a boot downloads exactly the group it seeds (see `BakedGroup`). */
export const BAKED_LANGUAGES: readonly BakedLanguage[] = ['glsl', 'wgsl']
export const BAKED_GROUPS: readonly BakedGroup[] = ['hillshade', 'rest']

/** Committed artifact file name per (language, group), relative to this directory. */
export const bakedArtifactFile = (language: BakedLanguage, group: BakedGroup): string =>
  `baked-${language}-${group}.generated.ts`

/** The const each artifact module exports. `baked-sync.test.ts` imports the four consts
 *  by name directly, and `seed-hillshade.ts` names the two hillshade ones in its dynamic
 *  import — so this spelling is a contract, not an internal detail. */
export const bakedExportName = (language: BakedLanguage, group: BakedGroup): string =>
  `BAKED_${language.toUpperCase()}_${group.toUpperCase()}`

/** Emit every registry key of `(language, group)` NOW and content-address the results.
 *
 *  Requires the host seams to be configured (`configureProjections`, and
 *  `applyBodyOption` for the body consts) — the same contract every draper emit has.
 *  Two ids sharing a hash MUST share the source; a hash collision is asserted away
 *  here rather than trusted, because the artifact would otherwise serve one shader's
 *  bytes for another.
 *
 *  The content store is per FILE, so a source shared across the split (the GLSL vertex
 *  stage hillshade and raster both spell) is stored in each file that addresses it.
 *  That is the price of the split and it is the right way round: the alternative is a
 *  shared chunk every group must download to resolve its own index. */
export function buildBakedArtifact(language: BakedLanguage, group: BakedGroup): BakedArtifact {
  const contents: Record<string, string> = {}
  const index: Record<string, string> = {}
  for (const key of BAKED_SHADER_KEYS) {
    if (key.language !== language || key.group !== group) continue
    const source = key.emit()
    const hash = bakedContentHash(source)
    const seen = contents[hash]
    if (seen !== undefined && seen !== source)
      throw new Error(
        `bake: content-hash collision on ${hash} (${key.id}) — two distinct sources share an address`,
      )
    contents[hash] = source
    index[key.id] = hash
  }
  return { meta: currentBakedMeta(), contents, index }
}

const sortedEntries = (o: Readonly<Record<string, string>>): [string, string][] =>
  Object.keys(o)
    .sort()
    .map((k) => [k, o[k] as string])

/** The TypeScript source of a committed artifact module.
 *
 *  One JSON-escaped line per entry — the LOC ceiling walker
 *  (`map/src/loc-ceiling-ratchet.test.ts`) counts NEWLINES over every non-test .ts
 *  under map/src, so a pretty-printed source (thousands of lines of shader text)
 *  would blow the 800-line new-file cap on the first family. Keys are sorted so the
 *  output is a function of the CONTENT, not of iteration order.
 *
 *  NO provenance header (no SHA, no timestamp): a branch commit stamped into a
 *  generated file stops being reachable the moment the PR squash-merges, which is
 *  exactly how #1397 turned main red for everyone. The regeneration COMMAND is the
 *  durable pointer; `baked-sync.test.ts` is what proves the bytes are current. */
export function renderBakedModule(
  language: BakedLanguage,
  group: BakedGroup,
  artifact: BakedArtifact,
): string {
  const name = bakedExportName(language, group)
  const upper = language.toUpperCase()
  const lines: string[] = [
    '// GENERATED by map/scripts/bake-shaders.ts — DO NOT EDIT. Regenerate: bun run bake:shaders',
    '//',
    `// The '${group}' group of the closed ${upper} shader set, baked at build time`,
    '// (#1678 / #1484 phase A). One file per (language, group) so a boot downloads only the',
    "// group it seeds; the 'rest' file is imported by nothing at runtime and the bundler",
    '// drops it. `contents` stores each DISTINCT source once, addressed by its content hash;',
    '// `index` maps every `map/src/shaders/baked/registry.ts` id onto its content.',
    '// `meta` pins the body consts + projection-graph fingerprint this bake is valid under.',
    '//',
    '// `baked-sync.test.ts` re-emits every registry key and byte-compares it against this',
    '// file, so a drifted artifact fails the suite rather than shipping a stale shader.',
    '',
    "import type { BakedArtifact } from './registry'",
    '',
    `export const ${name}: BakedArtifact = {`,
    '  meta: {',
    `    EARTH_R: ${artifact.meta.EARTH_R},`,
    `    EARTH_E2: ${artifact.meta.EARTH_E2},`,
    `    WGS84_A: ${artifact.meta.WGS84_A},`,
    `    WGS84_E2: ${artifact.meta.WGS84_E2},`,
    `    projectionFingerprint: ${JSON.stringify(artifact.meta.projectionFingerprint)},`,
    '  },',
    '  contents: {',
    ...sortedEntries(artifact.contents).map(
      ([hash, src]) => `    ${JSON.stringify(hash)}: ${JSON.stringify(src)},`,
    ),
    '  },',
    '  index: {',
    ...sortedEntries(artifact.index).map(
      ([id, hash]) => `    ${JSON.stringify(id)}: ${JSON.stringify(hash)},`,
    ),
    '  },',
    '}',
    '',
  ]
  return lines.join('\n')
}
