export { Lexer } from './lexer/lexer'
export { TokenType, type Token } from './lexer/tokens'
export { Parser } from './parser/parser'
export type * from './parser/ast'
export { serializeXGB, deserializeXGB, type BinaryScene } from './binary/format'
export { resolveColor } from './tokens/colors'
export { resolveUtilities, type ResolvedProperties } from './ir/utility-resolver'
export { lower } from './ir/lower'
export { emitCommands } from './ir/emit-commands'
export type { Scene, SourceDef, RenderNode, ColorValue, StrokeValue, OpacityValue, SizeValue, DataExpr, ZoomStop, ConditionalBranch } from './ir/render-node'
export { hexToRgba, rgbaToHex, colorNone, colorConstant, opacityConstant, sizeNone, sizeConstant } from './ir/render-node'
export { evaluate, type FeatureProps } from './eval/evaluator'
export { resolveImports, resolveImportsAsync, type FileReader, type AsyncFileReader } from './module/resolver'
export { optimize } from './ir/optimize'
export { classifyExpr, type ExprClass } from './ir/classify'
export { constFold } from './ir/const-fold'
export { exprToWGSL, collectFields } from './codegen/wgsl-expr'
export { generateShaderVariant, type ShaderVariant } from './codegen/shader-gen'
export { parseXGVTIndex, parseGPUReadyTile, parsePropertyTable, decompressTileData, TILE_FLAG_FULL_COVER, type XGVTIndex, type XGVTHeader, type TileIndexEntry } from './tiler/tile-format'
export { tileKey, tileKeyUnpack, tileKeyParent, tileKeyChildren, compileGeoJSONToTiles, compileGeoJSONToTilesAsync, compileSingleTile, decomposeFeatures, lonLatToMercF64, splitF64, packDSFUNPolygonVertices, packDSFUNLineVertices, augmentRingWithArc, tessellateLineToArrays, type GeometryPart, type PropertyTable, type PropertyFieldType, type CompiledTileSet, type CompiledTile, type TileLevel, type TilerOptions, type FeatureIdResolver } from './tiler/vector-tiler'
export { clipPolygonToRect, clipLineToRect } from './tiler/clip'
export { simplify, simplifyPolygon, simplifyLine, toleranceForZoom, mercatorToleranceForZoom } from './tiler/simplify'
export { interpolateGreatCircle, haversineDistance } from './tiler/geodesic'
export { type RingPolygon } from './tiler/encoding'
export { decodeMvtTile, type MvtDecodeOptions } from './input/mvt-decoder'
export type { GeoJSONFeature, GeoJSONGeometry } from './tiler/geojson-types'
