// baseline: a287648cb3b02b79f22b42e8841e07be506cbd6c
// fixture: bright-landuse-match13
// variant.key: bright-landuse-match13
// pick: false
// note: OFM Bright-shape — variant-heavy land-cover with 13-arm match chain (matchExpr perf-gate boundary).

const PI: f32 = 3.14159265;
const DEG2RAD: f32 = 0.01745329;
const EARTH_R: f32 = 6378137.0;
const MERCATOR_LAT_LIMIT: f32 = 85.051129;

fn apply_log_depth(pos: vec4<f32>, fc: f32) -> vec4<f32> {
  let z = ((log2(max(0.000001, (pos.w + 1.0))) * fc) * pos.w);
  return vec4<f32>(pos.x, pos.y, z, pos.w);
}

fn compute_log_frag_depth(view_w: f32, fc: f32) -> f32 {
  return (log2(max(0.000001, (view_w + 1.0))) * fc);
}


struct Uniforms {
  mvp: mat4x4<f32>,
  fill_color: vec4<f32>,
  stroke_color: vec4<f32>,
  // projection params: x=type, y=centerLon, z=centerLat, w=unused
  proj_params: vec4<f32>,
  // DSFUN camera position in tile-local Mercator meters, split high/low.
  // cam_h + cam_l = splitF64(cam_merc - tile_origin_merc), computed CPU-side
  // per tile per frame. The vertex shader computes
  //   rel = (pos_h - cam_h) + (pos_l - cam_l)
  // which cancels the tile-origin magnitude and preserves f64-equivalent
  // precision at any camera zoom.
  cam_h: vec2<f32>,
  cam_l: vec2<f32>,
  // Absolute tile origin in Mercator meters (for non-Mercator reconstruction).
  tile_origin_merc: vec2<f32>,
  opacity: f32,
  // Logarithmic depth factor: 1.0 / log2(camera_far + 1.0).
  // Packed by the renderer each frame; shaders use it to rewrite
  // position.z and frag_depth for Three.js-equivalent log depth.
  log_depth_fc: f32,
  // Packed pick ID: low16 = layerId (1..65535, 0 = no layer),
  // high16 = instanceId (reserved for WORLD_COPIES). Written into
  // the RG32Uint pick texture G channel via the 
  // template substitution.
  pick_id: u32,
  // Per-layer NDC-z bias to disambiguate coplanar fills under log-depth.
  // All polygon layers draw at z=0 (ground plane); at high pitch the
  // log-depth precision compresses (~10 effective bits at pitch 85°),
  // so coplanar fragments fight. Subtracting layer_depth_offset times
  // position.w from clip-space z shifts NDC z by layer_depth_offset,
  // making later layers always win the LEQUAL test. Caller sets this
  // to a small per-layer multiple (e.g. layerIndex * 1e-4). Positive
  // offset pushes the layer toward the camera (right-handed NDC z;
  // negative is near).
  // WGSL rounds struct size up to the largest member alignment (16,
  // from mat4x4 / vec4) so the now-two trailing 4-byte fields pad the
  // struct to a 160-byte total — same size as before.
  layer_depth_offset: f32,
  // Phase B vertex-compression: tile-local-meters extent of one tile
  // at this tile's zoom. Used by vs_main_quantized to dequant the
  // unorm16x2 polygon vertex back to local Mercator meters:
  //   local_m = pos_norm * tile_extent_m
  // tile_extent_m = 2π × R_earth / 2^tileZoom — written CPU-side per
  // tile per frame, packs into the existing uniform slot pad without
  // growing the struct past 160 bytes.
  tile_extent_m: f32,
  // 3D-extrusion height in METERS in world space. 0 = flat (default).
  // vs_main_quantized lifts the polygon vertex by this height in the
  // world-z direction; mvp transforms to clip space respecting camera
  // pitch. MVP for buildings: a constant per-layer height (e.g. 50m)
  // so polygons lift uniformly. Per-feature heights via PropertyTable
  // are a future extension.
  extrude_height_m: f32,
  // Per-tile clip mask in absolute Mercator meters (west, south,
  // east, north). Fragment shader discards if the fragment's world
  // position falls outside this rect. Used to clip parent-ancestor
  // fallback rendering to the visible tile area it's filling — a
  // z=11 parent's geometry covers a 16×16 z=15 child area, but for
  // any one visible-tile fallback only ONE child's worth should
  // render. Without clip the parent renders over neighboring
  // children too (some primary-loaded with their own buildings),
  // causing cross-z depth fights and "wrong building wins".
  //
  // Sentinel: clip_bounds.x (west) == -1e30 → no clip (skip
  // discard). Used for primary tiles where own geometry already
  // stays within own bounds — the fragment-shader cost would be
  // pure waste. Caller writes -1e30 for primary, real bounds for
  // fallback.
  //
  // Industry-standard equivalent: MapLibre's per-tile stencil ID
  // pre-pass + stencil-test at draw time. We use fragment discard
  // for the 1st-pass implementation (smaller refactor, same
  // visual outcome). Migration to hardware stencil is a follow-up
  // perf optimisation.
  clip_bounds: vec4<f32>,
  // Per-frame camera zoom (Mapbox-style fractional zoom level).
  // Sampled by the palette gradient lookup (P3 Step 3c, see
  // textureSampleLevel call sites generated by emitColorGradient
  // Sample) — the variant shader maps zoom into the gradient
  // atlas's U coord. Followed by 3 f32 pads (NOT vec3<f32>, whose
  // 16-byte alignment would push the struct to 208 bytes) so the
  // struct ends on a 16-byte boundary at exactly 192 bytes.
  zoom: f32,
  // 3D extrusion base — wall BOTTOM z in world metres (Mapbox
  // fill-extrusion-base). vs_main_quantized lifts the wall bottom
  // vertex to this value instead of z=0, carving a podium under
  // the building. 0 (default) keeps the existing flat-base
  // behaviour. Reused the first _pad_zoom_0 slot to avoid growing
  // the struct past 192 bytes.
  extrude_base_m: f32,
  // Mapbox fill-translate — CSS-px viewport offset on fills.
  // Positive x shifts the fill to the right; positive y shifts
  // down. Applied to clip-space (x, y) after the MVP transform in
  // vs_main_quantized (the standard viewport-anchor case). 0,0
  // default preserves the existing path. Map-anchor variant is not
  // yet wired (would shift in world coords before MVP); OFM hits
  // are viewport-anchored.
  fill_translate_x: f32,
  fill_translate_y: f32,
}

@group(0) @binding(0) var<uniform> u: Uniforms;
@group(0) @binding(1) var<storage, read> feat_data: array<f32>;

// iter-181/182 — fill-pattern Stage 2 sprite atlas. Bound on every
// polygon pipeline; stub 1x1 white until the IconStage finishes
// loading the real atlas. Sampled by fs_fill_pattern (iter-182) at
// world-derived UV; non-pattern fragment shaders ignore the binding.
// The sampler lives at binding 6 (separate from the variant-codegen
// palette_samp at binding 4) so the two declarations never collide.
@group(0) @binding(5) var sprite_atlas: texture_2d<f32>;
@group(0) @binding(6) var sprite_samp: sampler;

fn proj_mercator(lon_deg: f32, lat_deg: f32) -> vec2<f32> {
  let lat = clamp(lat_deg, (-MERCATOR_LAT_LIMIT), MERCATOR_LAT_LIMIT);
  let x = ((lon_deg * DEG2RAD) * EARTH_R);
  let y = (log(tan(((PI / 4.0) + ((lat * DEG2RAD) / 2.0)))) * EARTH_R);
  return vec2<f32>(x, y);
}

fn wrap_lon_delta(d: f32) -> f32 {
  if ((d > 180.0)) {
    return (d - (ceil(((d - 180.0) / 360.0)) * 360.0));
  }
  if ((d < -180.0)) {
    return (d + (ceil((((-d) - 180.0) / 360.0)) * 360.0));
  }
  return d;
}

fn proj_equirectangular_d(lon_rel: f32, lat_deg: f32) -> vec2<f32> {
  return vec2<f32>(((lon_rel * DEG2RAD) * EARTH_R), ((lat_deg * DEG2RAD) * EARTH_R));
}

fn proj_natural_earth_d(lon_rel: f32, lat_deg: f32) -> vec2<f32> {
  let lat = (lat_deg * DEG2RAD);
  let lat2 = (lat * lat);
  let lat4 = (lat2 * lat2);
  let lat6 = (lat2 * lat4);
  let x_scale = (((0.8707 - (lat2 * 0.131979)) + (lat4 * 0.013791)) - (lat6 * 0.0081435));
  let y_val = (lat * (1.007226 + (lat2 * (0.015085 + (lat2 * ((-0.044475 + (lat2 * 0.028874)) - (lat4 * 0.005916)))))));
  return vec2<f32>((((lon_rel * DEG2RAD) * x_scale) * EARTH_R), (y_val * EARTH_R));
}

fn proj_equirectangular(lon_deg: f32, lat_deg: f32, clon: f32) -> vec2<f32> {
  return proj_equirectangular_d(wrap_lon_delta((lon_deg - clon)), lat_deg);
}

fn proj_natural_earth(lon_deg: f32, lat_deg: f32, clon: f32) -> vec2<f32> {
  return proj_natural_earth_d(wrap_lon_delta((lon_deg - clon)), lat_deg);
}

fn unwrap_lon_near(value: f32, ref_v: f32) -> f32 {
  return (value - (floor((((value - ref_v) + 180.0) / 360.0)) * 360.0));
}

fn unwrap_rad_near(value: f32, ref_v: f32) -> f32 {
  let two_pi = (PI * 2.0);
  return (value - (floor((((value - ref_v) + PI) / two_pi)) * two_pi));
}

fn proj_orthographic(lon_deg: f32, lat_deg: f32, clon: f32, clat: f32) -> vec2<f32> {
  let lam = (lon_deg * DEG2RAD);
  let phi = (lat_deg * DEG2RAD);
  let l0 = (clon * DEG2RAD);
  let p0 = (clat * DEG2RAD);
  let x = ((EARTH_R * cos(phi)) * sin((lam - l0)));
  let y = (EARTH_R * ((cos(p0) * sin(phi)) - ((sin(p0) * cos(phi)) * cos((lam - l0)))));
  return vec2<f32>(x, y);
}

fn proj_azimuthal_equidistant(lon_deg: f32, lat_deg: f32, clon: f32, clat: f32) -> vec2<f32> {
  let lam = (lon_deg * DEG2RAD);
  let phi = (lat_deg * DEG2RAD);
  let l0 = (clon * DEG2RAD);
  let p0 = (clat * DEG2RAD);
  let cos_c = ((sin(p0) * sin(phi)) + ((cos(p0) * cos(phi)) * cos((lam - l0))));
  let c = acos(clamp(cos_c, -1.0, 1.0));
  if ((c < 0.0001)) {
    return vec2<f32>(0.0, 0.0);
  }
  let k = (c / sin(c));
  let x = (((EARTH_R * k) * cos(phi)) * sin((lam - l0)));
  let y = ((EARTH_R * k) * ((cos(p0) * sin(phi)) - ((sin(p0) * cos(phi)) * cos((lam - l0)))));
  return vec2<f32>(x, y);
}

fn proj_stereographic(lon_deg: f32, lat_deg: f32, clon: f32, clat: f32) -> vec2<f32> {
  let lam = (lon_deg * DEG2RAD);
  let phi = (lat_deg * DEG2RAD);
  let l0 = (clon * DEG2RAD);
  let p0 = (clat * DEG2RAD);
  let cos_c = ((sin(p0) * sin(phi)) + ((cos(p0) * cos(phi)) * cos((lam - l0))));
  if ((cos_c < -0.9)) {
    return vec2<f32>(1000000000000000.0, 1000000000000000.0);
  }
  let k = (2.0 / (1.0 + cos_c));
  let x = (((EARTH_R * k) * cos(phi)) * sin((lam - l0)));
  let y = ((EARTH_R * k) * ((cos(p0) * sin(phi)) - ((sin(p0) * cos(phi)) * cos((lam - l0)))));
  return vec2<f32>(x, y);
}

fn oblique_rot(lon_deg: f32, lat_deg: f32, clon: f32, clat: f32) -> vec2<f32> {
  let lam = (lon_deg * DEG2RAD);
  let phi = (lat_deg * DEG2RAD);
  let l0 = (clon * DEG2RAD);
  let p0 = (clat * DEG2RAD);
  let d_lam = (lam - l0);
  let phi_rot = asin(clamp(((sin(phi) * cos(p0)) - ((cos(phi) * sin(p0)) * cos(d_lam))), -1.0, 1.0));
  let lam_rot = atan2((cos(phi) * sin(d_lam)), ((sin(phi) * sin(p0)) + ((cos(phi) * cos(p0)) * cos(d_lam))));
  return vec2<f32>(lam_rot, phi_rot);
}

fn proj_oblique_mercator_d(lam_rot: f32, phi_rot: f32) -> vec2<f32> {
  let phi_clamped = clamp(phi_rot, (-(MERCATOR_LAT_LIMIT * DEG2RAD)), (MERCATOR_LAT_LIMIT * DEG2RAD));
  let x = (EARTH_R * lam_rot);
  let y = (EARTH_R * log(tan(((PI / 4.0) + (phi_clamped / 2.0)))));
  return vec2<f32>(x, y);
}

fn proj_oblique_mercator(lon_deg: f32, lat_deg: f32, clon: f32, clat: f32) -> vec2<f32> {
  let r = oblique_rot(lon_deg, lat_deg, clon, clat);
  return proj_oblique_mercator_d(r.x, r.y);
}

fn proj_globe(lon_deg: f32, lat_deg: f32) -> vec3<f32> {
  let lam = (lon_deg * DEG2RAD);
  let phi = (lat_deg * DEG2RAD);
  let cphi = cos(phi);
  return vec3<f32>(((EARTH_R * cphi) * cos(lam)), ((EARTH_R * cphi) * sin(lam)), (EARTH_R * sin(phi)));
}

fn center_cos_c(lon_deg: f32, lat_deg: f32, clon: f32, clat: f32) -> f32 {
  let lam = (lon_deg * DEG2RAD);
  let phi = (lat_deg * DEG2RAD);
  let l0 = (clon * DEG2RAD);
  let p0 = (clat * DEG2RAD);
  return ((sin(p0) * sin(phi)) + ((cos(p0) * cos(phi)) * cos((lam - l0))));
}

fn project(lon_deg: f32, lat_deg: f32, proj_params: vec4<f32>) -> vec2<f32> {
  let t = proj_params.x;
  let clon = proj_params.y;
  let clat = proj_params.z;
  if ((t < 0.5)) {
    return proj_mercator(lon_deg, lat_deg);
  } else if ((t < 1.5)) {
    return proj_equirectangular(lon_deg, lat_deg, clon);
  } else if ((t < 2.5)) {
    return proj_natural_earth(lon_deg, lat_deg, clon);
  } else if ((t < 3.5)) {
    return proj_orthographic(lon_deg, lat_deg, clon, clat);
  } else if ((t < 4.5)) {
    return proj_azimuthal_equidistant(lon_deg, lat_deg, clon, clat);
  } else if ((t < 5.5)) {
    return proj_stereographic(lon_deg, lat_deg, clon, clat);
  } else {
    return proj_oblique_mercator(lon_deg, lat_deg, clon, clat);
  }
}

fn project_geom(lon_deg: f32, lat_deg: f32, proj_params: vec4<f32>, ref_lon: f32) -> vec2<f32> {
  let t = proj_params.x;
  let clon = proj_params.y;
  let clat = proj_params.z;
  if (((t > 0.5) && (t < 2.5))) {
    let wo = floor((((ref_lon - clon) + 180.0) / 360.0));
    let lon_primary = (lon_deg - (wo * 360.0));
    let ref_primary = (ref_lon - (wo * 360.0));
    let ref_d = wrap_lon_delta((ref_primary - clon));
    let d = unwrap_lon_near((lon_primary - clon), ref_d);
    let world_off_m = (((wo * 2.0) * PI) * EARTH_R);
    var p: vec2<f32>;
    if ((t < 1.5)) {
      p = proj_equirectangular_d(d, lat_deg);
    } else {
      p = proj_natural_earth_d(d, lat_deg);
    }
    p.x = (p.x + world_off_m);
    return p;
  }
  if ((t > 5.5)) {
    let wo = floor((((ref_lon - clon) + 180.0) / 360.0));
    let lon_primary = (lon_deg - (wo * 360.0));
    let ref_primary = (ref_lon - (wo * 360.0));
    let r = oblique_rot(lon_primary, lat_deg, clon, clat);
    let ref_r = oblique_rot(ref_primary, clat, clon, clat);
    let lam_u = unwrap_rad_near(r.x, ref_r.x);
    var p: vec2<f32> = proj_oblique_mercator_d(lam_u, r.y);
    p.x = (p.x + (((wo * 2.0) * PI) * EARTH_R));
    return p;
  }
  return project(lon_deg, lat_deg, proj_params);
}

fn needs_backface_cull(lon_deg: f32, lat_deg: f32, proj_params: vec4<f32>) -> f32 {
  let t = proj_params.x;
  let clon = proj_params.y;
  let clat = proj_params.z;
  if ((t > 2.5)) {
    let cc = center_cos_c(lon_deg, lat_deg, clon, clat);
    if ((t < 3.5)) {
      return cc;
    }
    if ((t < 4.5)) {
      return select(-1.0, 1.0, (cc > -0.85));
    }
    if ((t < 5.5)) {
      return select(-1.0, 1.0, (cc > -0.8));
    }
    if ((t < 6.5)) {
      return 1.0;
    }
    return cc;
  }
  return 1.0;
}

fn rim_alpha(lon_deg: f32, lat_deg: f32, proj_params: vec4<f32>) -> f32 {
  let t = proj_params.x;
  let clon = proj_params.y;
  let clat = proj_params.z;
  if ((t > 2.5)) {
    let cc = center_cos_c(lon_deg, lat_deg, clon, clat);
    if ((t < 3.5)) {
      return smoothstep(0.0, 0.02, cc);
    }
    if ((t < 4.5)) {
      return smoothstep(-0.85, -0.83, cc);
    }
    if ((t < 5.5)) {
      return smoothstep(-0.8, -0.78, cc);
    }
    if ((t < 6.5)) {
      return 1.0;
    }
    return smoothstep(0.0, 0.02, cc);
  }
  return 1.0;
}

fn inv_merc_lat_rad(merc_y_m: f32) -> f32 {
  return ((2.0 * atan(exp((merc_y_m / EARTH_R)))) - (PI / 2.0));
}


// Per-fragment recompute of the hemisphere-cull signal. The vertex
// shader emits cos_c as a varying (location 0), but cos_c is a non-
// linear function of position — linear interpolation across a triangle
// spanning the visible-hemisphere boundary on globe / orthographic /
// azimuthal projections diverges from the true per-fragment value.
// A long polygon edge crossing the terminator can interpolate to a
// positive cos_c even where the fragment is on the back hemisphere
// (false visibility), or to a negative cos_c where it is on the front
// (false hole). Recompute from the absolute-Mercator varyings (which
// telescope exactly under linear interpolation) and call the shared
// needs_backface_cull entry that the vertex path uses.
//
// Cost: 1 atan + 1 exp + a few muls per fragment in the cull path.
// Flat projections (proj_params.x < 2.5) short-circuit inside
// needs_backface_cull to +1 so the per-pixel cost stays at ~0 for the
// common Mercator / equirect / natural-earth cases.
//
// Pattern mirrors line-renderer.ts:779 and point-renderer.ts:340,
// which already recompute per-fragment after the same vertex-
// interpolation correctness regression was identified for those
// renderers.
fn polygon_cos_c_fragment(abs_merc_x: f32, abs_merc_y: f32) -> f32 {
  let abs_lon = abs_merc_x / (DEG2RAD * EARTH_R);
  let lat_rad = inv_merc_lat_rad(abs_merc_y);
  let abs_lat = lat_rad / DEG2RAD;
  return needs_backface_cull(abs_lon, abs_lat, u.proj_params);
}

// Companion to polygon_cos_c_fragment: continuous-alpha rim fade
// (smoothstep across the visibility boundary). Fragment shaders
// multiply this into output alpha so geometry on the sphere rim
// fades smoothly instead of popping at the cos_c=0 boundary. Cost
// is one extra needs_backface_cull-equivalent call; safe to leave
// on for all projections (returns 1.0 for flat / cylindrical).
fn polygon_rim_alpha(abs_merc_x: f32, abs_merc_y: f32) -> f32 {
  let abs_lon = abs_merc_x / (DEG2RAD * EARTH_R);
  let lat_rad = inv_merc_lat_rad(abs_merc_y);
  let abs_lat = lat_rad / DEG2RAD;
  return rim_alpha(abs_lon, abs_lat, u.proj_params);
}

struct VertexOutput {
  @builtin(position) position: vec4<f32>,
  @location(0) cos_c: f32,
  @location(1) @interpolate(flat) feat_id: u32,
  @location(2) abs_lat: f32,
  // view_w = pre-division clip-space w. Fragment shader recomputes
  // log-depth per pixel from this (linear interpolation of log2 over
  // a triangle would drift otherwise).
  @location(3) view_w: f32,
  // 3D extrusion shading factor. is_top=1 (roof) → 1.0; is_top=0
  // (wall bottom) → 0.0; the value interpolates 0..1 along wall
  // triangles. Fragment uses to mix between dark wall + bright
  // roof colour for a poor-man's Lambert without a real normal.
  @location(4) wall_blend: f32,
  // Absolute mercator world position. Forwarded from the vertex
  // shader so the fragment can clip-test against u.clip_bounds.
  // Costs 8 bytes per vertex output but avoids reconstructing the
  // world position from view_w in the fragment.
  @location(5) abs_merc_x: f32,
  @location(6) abs_merc_y: f32,
  // World-space z (extrude height) — fragment computes face normal
  // via cross(dFdx, dFdy) on (abs_merc_x, abs_merc_y, world_z) for
  // directional shading. Iter 128 building-light fix.
  @location(7) world_z: f32,
  // iter-194 — MapLibre-equivalent fill-extrusion lighting. The
  // extrude vertex shader computes per-vertex face-normal directional
  // lighting + vertical-gradient and emits the final pre-shaded
  // color (PREMULTIPLIED alpha) here. fs_fill_extrude returns this
  // verbatim; other fragment shaders ignore. Non-extrude vertex
  // shaders write vec4(0,0,0,0) — they have no normal attribute.
  @location(8) v_color: vec4<f32>,
}

struct FragmentOutput {
  @location(0) color: vec4<f32>,
  
  @builtin(frag_depth) depth: f32,
}

@vertex
fn vs_main(
  @location(0) pos_h: vec2<f32>,
  @location(1) pos_l: vec2<f32>,
  @location(2) feature_id: f32,
) -> VertexOutput {
  // DSFUN Mercator subtraction — camera-relative tile-local meters.
  // (pos_h - cam_h) + (pos_l - cam_l) = pos_f64 - cam_f64 with f64-equivalent
  // precision, because the large tile-origin magnitude cancels before the low
  // parts are added.
  let rel = (pos_h - u.cam_h) + (pos_l - u.cam_l);

  // Reconstruct absolute Mercator meters (needed for non-Mercator
  // reprojection and for the fragment discard at |lat| > MERCATOR_LAT_LIMIT).
  let abs_merc_x = (pos_h.x + pos_l.x) + u.tile_origin_merc.x;
  let abs_merc_y = (pos_h.y + pos_l.y) + u.tile_origin_merc.y;
  let abs_lon = abs_merc_x / (DEG2RAD * EARTH_R);
  let lat_rad = inv_merc_lat_rad(abs_merc_y);
  let abs_lat = lat_rad / DEG2RAD;
  let abs_lat_clamped = clamp(abs_lat, -MERCATOR_LAT_LIMIT, MERCATOR_LAT_LIMIT);

  let t = u.proj_params.x;
  var rtc: vec2<f32>;
  if (t < 0.5) {
    // Pure Mercator: rel is already camera-relative meters.
    rtc = rel;
  } else {
    // All other projections (equirect, natural earth, ortho, ...):
    // run the same project() as before but on the reconstructed absolute
    // lon/lat, then subtract the projected camera center. Precision here is
    // limited to the f32 reconstruction, which is fine because non-Mercator
    // projections are only used at low/global zoom.
    // NOTE: avoid the reserved word "target" as an identifier.
    // Tile centre longitude — the per-tile unwrap reference that keeps a
    // seam-straddling tile contiguous under equirect / natural_earth.
    let tile_ref_lon = (u.tile_origin_merc.x + 0.5 * u.tile_extent_m) / (DEG2RAD * EARTH_R);
    let proj_xy = project_geom(abs_lon, abs_lat, u.proj_params, tile_ref_lon);
    let center_xy = project(u.proj_params.y, u.proj_params.z, u.proj_params);
    rtc = proj_xy - center_xy;
  }
  // True 3D globe (projType 7): RTC against the focus point ON THE
  // sphere, then the orbit-camera MVP the camera emits in globe mode.
  let globe_rtc = proj_globe(abs_lon, abs_lat) - proj_globe(u.proj_params.y, u.proj_params.z);

  var out: VertexOutput;
  var clip = select(
    u.mvp * vec4<f32>(rtc, 0.0, 1.0),
    u.mvp * vec4<f32>(globe_rtc, 1.0),
    t > 6.5,
  );
  // Mapbox fill-translate (viewport anchor) — see vs_main_quantized
  // for the math. Same pre-baked ndc-per-pixel constant applied here
  // so the non-quantized path stays in sync.
  clip.x = clip.x + u.fill_translate_x * clip.w;
  clip.y = clip.y - u.fill_translate_y * clip.w;
  // Log-depth rewrite of clip.z. Three.js equivalent — preserves near-plane
  // precision at high pitch and when rendering 3D geometry.
  out.position = apply_log_depth(clip, u.log_depth_fc);
  // Per-layer z bias (see Uniforms.layer_depth_offset). Multiplied by
  // post-projection w so the NDC-z shift is constant across the depth
  // range (perspective-divide cancels the w factor).
  out.position.z = out.position.z - u.layer_depth_offset * out.position.w;
  out.view_w = clip.w;
  // cos_c kept as a varying-layout placeholder — fragments now
  // recompute hemisphere cull per-pixel via polygon_cos_c_fragment()
  // (commit c205871) since linear interpolation of cos_c across
  // large triangles diverges from the true sphere distance. Writing
  // 0 avoids the per-vertex needs_backface_cull() call which on
  // globe/ortho computes sin/cos; flat projections were already a
  // no-op (returns 1.0) so this is a perf win on the projection
  // paths that benefit AND a clarity win everywhere else (no
  // misleading "this varying gets read" implication).
  out.cos_c = 0.0;
  out.feat_id = u32(feature_id);
  out.abs_lat = abs_lat_clamped;
  out.wall_blend = 1.0; // DSFUN line pipeline isn't extruded; full brightness
  out.abs_merc_x = abs_merc_x;
  out.abs_merc_y = abs_merc_y;
  out.world_z = 0.0; // non-extruded path
  out.v_color = vec4<f32>(0.0); // iter-194 — only the extrude path emits
  return out;
}

// Phase B quantized polygon vertex entry. Reads pos_raw (uint16x2 →
// vec2<u32> in shader) and unpacks:
//   - bit 15 of x  : is_top flag (3D extrusion side-wall support)
//   - bits 0-14    : 15-bit position quanta in [0, 32767]
//
// The 1-bit precision sacrifice on x (32767 vs 65535 quanta over a
// tile) is sub-pixel even at zoom 22 (9.5 m / 32767 ≈ 0.29 mm) so
// invisible in any rendering.
//
// Bottom and top vertices share the same x,y; only the is_top flag
// differs. vs_main_quantized lifts top vertices to z=extrude_height_m
// in world space; bottom vertices stay on the ground plane (z=0).
// Side walls between (a_bot, b_bot, a_top, b_top) thus form a vertical
// quad without needing a separate vertex format or pipeline.
@vertex
fn vs_main_quantized(
  @location(0) pos_raw: vec2<u32>,
  @location(2) feature_id: f32,
) -> VertexOutput {
  let is_top = (pos_raw.x & 0x8000u) != 0u;
  let mx_q = f32(pos_raw.x & 0x7FFFu);
  let my_q = f32(pos_raw.y);
  let local = vec2<f32>(mx_q, my_q) / 32767.0 * u.tile_extent_m;
  // cam_h + cam_l = cam_merc - tile_origin_merc (set CPU-side). Sum
  // here is fine because we are already at tile-local scale where Float32
  // suffices. Same downstream as vs_main from rel onward.
  let cam_local = u.cam_h + u.cam_l;
  let rel = local - cam_local;

  let abs_merc_x = local.x + u.tile_origin_merc.x;
  let abs_merc_y = local.y + u.tile_origin_merc.y;
  let abs_lon = abs_merc_x / (DEG2RAD * EARTH_R);
  let lat_rad = inv_merc_lat_rad(abs_merc_y);
  let abs_lat = lat_rad / DEG2RAD;
  let abs_lat_clamped = clamp(abs_lat, -MERCATOR_LAT_LIMIT, MERCATOR_LAT_LIMIT);

  let t = u.proj_params.x;
  var rtc: vec2<f32>;
  if (t < 0.5) {
    rtc = rel;
  } else {
    let tile_ref_lon = (u.tile_origin_merc.x + 0.5 * u.tile_extent_m) / (DEG2RAD * EARTH_R);
    let proj_xy = project_geom(abs_lon, abs_lat, u.proj_params, tile_ref_lon);
    let center_xy = project(u.proj_params.y, u.proj_params.z, u.proj_params);
    rtc = proj_xy - center_xy;
  }
  let globe_rtc = proj_globe(abs_lon, abs_lat) - proj_globe(u.proj_params.y, u.proj_params.z);

  var out: VertexOutput;
  // 3D extrusion: top vertices lift to z=extrude_height_m, bottom
  // stay at z=0. Wall quads (a_bot, b_bot, a_top, b_top) form
  // vertical sides; top-face polygons all carry is_top=1. Non-
  // extruded layers set extrude_height_m=0 → both branches yield
  // z=0 → identical to the flat path.
  // Walls run from extrude_base_m (default 0) to extrude_height_m.
  // is_top=1 → roof at extrude_height_m; is_top=0 → wall bottom at
  // extrude_base_m. Mapbox fill-extrusion-base controls the
  // bottom; pre-fix it was always 0 even when authored otherwise.
  let z_world = select(u.extrude_base_m, u.extrude_height_m, is_top);
  // Globe (projType 7) uses the sphere RTC + orbit MVP; extrusion on
  // the sphere is a later refinement (flat basemap path unaffected).
  var clip = select(
    u.mvp * vec4<f32>(rtc, z_world, 1.0),
    u.mvp * vec4<f32>(globe_rtc, 1.0),
    t > 6.5,
  );
  // Mapbox fill-translate (viewport anchor): shift clip-space xy by
  // tx/ty pixels. The runtime pre-bakes (px * 2 / canvasDim) into
  // fill_translate_x/y so the shader just multiplies by clip.w
  // (undoes perspective divide so the offset stays constant in
  // SCREEN pixels regardless of depth). y is negated since Mapbox
  // spec defines positive y as DOWN while our NDC y is UP.
  clip.x = clip.x + u.fill_translate_x * clip.w;
  clip.y = clip.y - u.fill_translate_y * clip.w;
  out.position = apply_log_depth(clip, u.log_depth_fc);
  out.position.z = out.position.z - u.layer_depth_offset * out.position.w;
  out.view_w = clip.w;
  // cos_c kept as a varying-layout placeholder — fragments now
  // recompute hemisphere cull per-pixel via polygon_cos_c_fragment()
  // (commit c205871) since linear interpolation of cos_c across
  // large triangles diverges from the true sphere distance. Writing
  // 0 avoids the per-vertex needs_backface_cull() call which on
  // globe/ortho computes sin/cos; flat projections were already a
  // no-op (returns 1.0) so this is a perf win on the projection
  // paths that benefit AND a clarity win everywhere else (no
  // misleading "this varying gets read" implication).
  out.cos_c = 0.0;
  out.feat_id = u32(feature_id);
  out.abs_lat = abs_lat_clamped;
  // Wall shading only meaningful when this layer is extruded; for
  // flat layers all geometry is at the roof brightness.
  out.wall_blend = select(1.0, select(0.0, 1.0, is_top), u.extrude_height_m > 0.0);
  out.abs_merc_x = abs_merc_x;
  out.abs_merc_y = abs_merc_y;
  out.world_z = z_world;
  out.v_color = vec4<f32>(0.0); // iter-194 — flat path has no normal attr
  return out;
}

// Per-feature 3D extrusion entry. Same as vs_main_quantized but z
// comes from a parallel vertex buffer (location 3) instead of
// is_top times u.extrude_height_m. Bound when the upload path took
// the *Extruded mesh-gen variants — i.e. an MVT slice that carried
// per-feature render_height / height properties.
//
// wall_blend is derived from the z attribute: z>0 -> 1.0 (top / roof),
// z=0 -> 0.0 (bottom of wall). Roof faces get full brightness; walls
// fade from base to roof exactly like the uniform path.
@vertex
fn vs_main_quantized_extruded(
  @location(0) pos_raw: vec2<u32>,
  @location(2) feature_id: f32,
  @location(3) z_attr: vec4<f32>,  // iter-194 — .x=z, .yzw=outward unit normal
) -> VertexOutput {
  let mx_q = f32(pos_raw.x & 0x7FFFu);
  let my_q = f32(pos_raw.y);
  let local = vec2<f32>(mx_q, my_q) / 32767.0 * u.tile_extent_m;
  let cam_local = u.cam_h + u.cam_l;
  let rel = local - cam_local;

  let abs_merc_x = local.x + u.tile_origin_merc.x;
  let abs_merc_y = local.y + u.tile_origin_merc.y;
  let abs_lon = abs_merc_x / (DEG2RAD * EARTH_R);
  let lat_rad = inv_merc_lat_rad(abs_merc_y);
  let abs_lat = lat_rad / DEG2RAD;
  let abs_lat_clamped = clamp(abs_lat, -MERCATOR_LAT_LIMIT, MERCATOR_LAT_LIMIT);

  let t = u.proj_params.x;
  var rtc: vec2<f32>;
  if (t < 0.5) {
    rtc = rel;
  } else {
    let tile_ref_lon = (u.tile_origin_merc.x + 0.5 * u.tile_extent_m) / (DEG2RAD * EARTH_R);
    let proj_xy = project_geom(abs_lon, abs_lat, u.proj_params, tile_ref_lon);
    let center_xy = project(u.proj_params.y, u.proj_params.z, u.proj_params);
    rtc = proj_xy - center_xy;
  }
  let globe_rtc = proj_globe(abs_lon, abs_lat) - proj_globe(u.proj_params.y, u.proj_params.z);

  // iter-194 — unpack z + normal from the vec4 attribute.
  let z_world = z_attr.x;
  let normal = z_attr.yzw;

  var out: VertexOutput;
  var clip = select(
    u.mvp * vec4<f32>(rtc, z_world, 1.0),
    u.mvp * vec4<f32>(globe_rtc, 1.0),
    t > 6.5,
  );
  // Mapbox fill-translate — viewport anchor (see vs_main_quantized
  // for the math). Per-feature-z (extruded) path applies the same
  // pixel offset so building roofs / walls stay aligned with the
  // un-extruded ground plane.
  clip.x = clip.x + u.fill_translate_x * clip.w;
  clip.y = clip.y - u.fill_translate_y * clip.w;
  out.position = apply_log_depth(clip, u.log_depth_fc);
  out.position.z = out.position.z - u.layer_depth_offset * out.position.w;
  out.view_w = clip.w;
  out.cos_c = 0.0;
  out.feat_id = u32(feature_id);
  out.abs_lat = abs_lat_clamped;
  out.wall_blend = select(0.0, 1.0, z_world > 0.0);
  out.abs_merc_x = abs_merc_x;
  out.abs_merc_y = abs_merc_y;
  out.world_z = z_world;

  // iter-194 — MapLibre-equivalent face-normal directional lighting.
  // Direct port of fill_extrusion.vertex.glsl, with the default
  // light style:
  //   light.position = [1.15, 210°, 30°]  → cartesian (0.288, -0.498, 0.996)
  //   light.intensity = 0.5
  //   light.color = (1, 1, 1)
  //   fill-extrusion-vertical-gradient default = 1.0
  let color_rgb = u.fill_color.rgb;
  let opacity = u.fill_color.a;
  let colorvalue = color_rgb.r * 0.2126 + color_rgb.g * 0.7152 + color_rgb.b * 0.0722;
  let ambient = vec3<f32>(0.03);
  let lit_color_rgb = color_rgb + ambient;
  let LIGHT_POS = vec3<f32>(0.288, -0.498, 0.996);
  let LIGHT_INTENSITY = 0.5;
  let LIGHT_COLOR = vec3<f32>(1.0);
  var directional = clamp(dot(normal, LIGHT_POS), 0.0, 1.0);
  directional = mix(
    1.0 - LIGHT_INTENSITY,
    max(1.0 - colorvalue + LIGHT_INTENSITY, 1.0),
    directional,
  );
  // Vertical gradient — walls only (nz≈0). t = is_top boolean.
  let is_wall = abs(normal.z) < 0.5;
  let t_top = select(0.0, 1.0, z_world > 0.0);
  if (is_wall) {
    // (t + base) * sqrt(height/150). With our z_world packing,
    // wall-top z_world = feature_height, wall-bottom z_world = 0
    // (or base — treated as 0 for the gradient term in MapLibre too).
    // Approximate feature height by max(z_world, 1) for the bottom
    // vertex's compute; the bottom always lands at the lower bound.
    let h_for_grad = max(z_world, 1.0);
    let vgrad = clamp(
      (t_top) * sqrt(h_for_grad / 150.0),
      mix(0.7, 0.98, 1.0 - LIGHT_INTENSITY),
      1.0,
    );
    directional = directional * vgrad;
  }
  let shaded_rgb = clamp(lit_color_rgb * directional * LIGHT_COLOR, vec3<f32>(0.0), vec3<f32>(1.0));
  // iter-194 — non-premultiplied output so X-GIS' existing
  // BLEND_ALPHA (srcFactor=src-alpha) produces the same final
  // blend math MapLibre's BLEND_ALPHA_PREMULT (srcFactor=one) does
  // on its pre-multiplied output. Both reduce to
  //   final = src.rgb * src.a + dst * (1 - src.a)
  // — exact equivalence.
  out.v_color = vec4<f32>(shaded_rgb, opacity);
  return out;
}

// ── Fragment shaders (replaceable by ShaderVariant) ──
// FILL_EXPR and STROKE_EXPR are replaced by buildShader() when a variant exists

@fragment
fn fs_fill(input: VertexOutput) -> FragmentOutput {
  // Per-fragment recompute (see polygon_cos_c_fragment doc above).
  // Interpolating the per-vertex cos_c across a triangle that crosses
  // the visible-hemisphere boundary diverges from the true sphere
  // distance, so vertex-only cull leaks fragments on the back
  // hemisphere or punches false holes on the front. The fragment
  // recompute uses abs_merc_x/y, which DO telescope exactly under
  // linear interpolation.
  if (polygon_cos_c_fragment(input.abs_merc_x, input.abs_merc_y) < 0.0) { discard; }
  if (abs(input.abs_lat) > MERCATOR_LAT_LIMIT) { discard; }
  // Per-tile clip mask: only apply when ALL FOUR sides describe a
  // valid bounding box (east > west AND north > south). The sentinel
  // -1e30 trips the first check; the validity check catches the case
  // where some upstream path forgot to write all four fields and
  // left partial / stale data — without it, a (0, 0, 0, 0) residue
  // would silently discard most of the world (symptom: hero map
  // shows only ~1/4 of the globe — Africa + Australia only).
  let _clip_valid =
    u.clip_bounds.x > -1e29 &&
    u.clip_bounds.z > u.clip_bounds.x &&
    u.clip_bounds.w > u.clip_bounds.y;
  if (_clip_valid) {
    if (input.abs_merc_x < u.clip_bounds.x) { discard; }
    if (input.abs_merc_x > u.clip_bounds.z) { discard; }
    if (input.abs_merc_y < u.clip_bounds.y) { discard; }
    if (input.abs_merc_y > u.clip_bounds.w) { discard; }
  }
  var out: FragmentOutput;
  // Fill-extrusion shading — iter 128 directional light via fragment
  // screen-space derivatives. Iter 129 tweak: use tile-local position
  // for derivatives (abs_merc_x/y are 1e7 m at typical zooms; dFdx
  // of large numbers loses precision and adds graininess to walls).
  //
  // Face normal is computed as cross(dFdx(p), dFdy(p)) where p is in
  // tile-local meters + world z. Wall fragments → horizontal outward
  // normal; roof fragments → +Z. abs() the dot product so winding
  // doesn't matter.
  //
  // Light direction matches MapLibre default (~SSW + 30° elevation):
  // light_dir ≈ (-0.4, -0.7, 0.6).
  // Iter 129 final: derivative-based normal proved too noisy at z>=17
  // (fragment 2x2 quads span multiple small triangles → mixed normal).
  // Restore vertical gradient + roof_bonus for stable shading; proper
  // per-vertex normal attribute is a separate refactor.
  let v_shade = 0.6 + 0.4 * input.wall_blend;
  let roof_bonus = select(0.0, 0.05, input.wall_blend >= 0.999);
  let wall_shade = min(1.0, v_shade + roof_bonus);
  var _mcB1: vec4f = vec4f(0.78, 0.78, 0.78, 1.0);
  if (field0_id == 0u) { _mcB1 = vec4f(0.78, 0.91, 0.74, 1.00); }
  else if (field0_id == 1u) { _mcB1 = vec4f(0.92, 0.86, 0.65, 1.00); }
  else if (field0_id == 2u) { _mcB1 = vec4f(0.84, 0.80, 0.70, 1.00); }
  else if (field0_id == 3u) { _mcB1 = vec4f(0.69, 0.85, 0.69, 1.00); }
  else if (field0_id == 4u) { _mcB1 = vec4f(0.95, 0.78, 0.78, 1.00); }
  else if (field0_id == 5u) { _mcB1 = vec4f(0.71, 0.78, 0.83, 1.00); }
  else if (field0_id == 6u) { _mcB1 = vec4f(0.87, 0.74, 0.62, 1.00); }
  else if (field0_id == 7u) { _mcB1 = vec4f(0.62, 0.74, 0.87, 1.00); }
  else if (field0_id == 8u) { _mcB1 = vec4f(0.81, 0.67, 0.55, 1.00); }
  else if (field0_id == 9u) { _mcB1 = vec4f(0.55, 0.81, 0.67, 1.00); }
  else if (field0_id == 10u) { _mcB1 = vec4f(0.67, 0.55, 0.81, 1.00); }
  else if (field0_id == 11u) { _mcB1 = vec4f(0.79, 0.79, 0.79, 1.00); }
  else if (field0_id == 12u) { _mcB1 = vec4f(0.91, 0.91, 0.78, 1.00); }  out.color = _mcB1;
  // Rim alpha: smooth fade across the sphere visibility boundary so
  // geometry at cos_c ≈ 0 (globe / ortho / azimuthal / stereographic
  // edges) doesn't flicker as the per-fragment cos_c sign flips
  // between frames. Returns 1.0 on flat / cylindrical projections
  // — no-op there. Applied AFTER the marker-replaceable out.color
  // line so variant pipelines (data-driven match → fillExpr) still
  // get rim fade without per-variant codegen plumbing.
  out.color.a = out.color.a * polygon_rim_alpha(input.abs_merc_x, input.abs_merc_y);
  
  // Per-feature deterministic depth jitter to break coplanar z-fights
  // at shared walls between adjacent buildings. Two buildings that
  // share an edge each emit a wall along that edge at z=0..min(H_A,
  // H_B) — fragments at the same screen pixel on both walls compute
  // the same view_w, so log-depth is identical and the GPU resolves
  // the tie from per-pixel rasterisation noise (visible "sparkle"
  // along the shared base, reported by user at Tokyo z=16.33
  // pitch=63.5°). A tiny per-feat_id offset shifts each feature's
  // depth by a deterministic amount well below visible pixel scale,
  // so adjacent walls always have a consistent winner.
  //   range: ±FEAT_DEPTH_JITTER ≈ ±1.5e-5 NDC z (24-bit depth = 6e-8
  //   per unit → ~250 depth units, sub-pixel visually).
  // Only applied when feat_id is non-zero — synthetic pseudo-features
  // (background quads etc.) keep the canonical log-depth result.
  //
  // Bitwise hash (xor-shift mix) on the LOW 16 bits of feat_id
  // avoids u32 multiplication overflow that some implementations
  // (notably Apple Metal under iOS Safari) treat as a shader-
  // validation error. Pure shifts + xor stay strictly within the
  // unsigned domain WGSL specifies as wrap-on-overflow.
  let base_depth = compute_log_frag_depth(input.view_w, u.log_depth_fc);
  let id_lo = input.feat_id & 0xFFFFu;
  let mixed = (id_lo ^ (id_lo >> 7u) ^ (id_lo << 3u)) & 0x3FFu; // 0..1023
  let jitter = select(
    0.0,
    (f32(mixed) - 512.0) * 1.5e-8,
    input.feat_id != 0u,
  );
  out.depth = base_depth + jitter;
  return out;
}

// iter-182 — fill-pattern Stage 2 fragment. Mirrors fs_fill's
// hemisphere-cull + clip discard + log-depth jitter, but the final
// out.color assignment samples the sprite atlas instead of using
// the solid u.fill_color. Pattern parameters travel in REUSED
// uniform slots so the Uniforms struct stays at 192 bytes:
//   u.fill_color.rgba  = (u0, v0, u1, v1) in atlas UV [0..1]
//   u.fill_translate_x = pattern repeat in absolute Mercator metres
//   u.fill_translate_y = pattern repeat in absolute Mercator metres
// (Pattern-fill layers cannot also use a solid fill colour or a
// fill-translate offset; that is the documented Stage 2 trade-off.)
@fragment
fn fs_fill_pattern(input: VertexOutput) -> FragmentOutput {
  if (polygon_cos_c_fragment(input.abs_merc_x, input.abs_merc_y) < 0.0) { discard; }
  if (abs(input.abs_lat) > MERCATOR_LAT_LIMIT) { discard; }
  let _clip_valid =
    u.clip_bounds.x > -1e29 &&
    u.clip_bounds.z > u.clip_bounds.x &&
    u.clip_bounds.w > u.clip_bounds.y;
  if (_clip_valid) {
    if (input.abs_merc_x < u.clip_bounds.x) { discard; }
    if (input.abs_merc_x > u.clip_bounds.z) { discard; }
    if (input.abs_merc_y < u.clip_bounds.y) { discard; }
    if (input.abs_merc_y > u.clip_bounds.w) { discard; }
  }
  var out: FragmentOutput;
  // Sprite UV: world-anchored repeating tile via abs_merc / repeat_m.
  // fract wraps the local UV into [0, 1); u0 + frac * (u1 - u0)
  // remaps that into the sprite atlas-UV bbox.
  let repeat_x = max(u.fill_translate_x, 1.0);
  let repeat_y = max(u.fill_translate_y, 1.0);
  let uv_local = vec2<f32>(
    fract(input.abs_merc_x / repeat_x),
    fract(input.abs_merc_y / repeat_y),
  );
  let u0 = u.fill_color.r; let v0 = u.fill_color.g;
  let u1 = u.fill_color.b; let v1 = u.fill_color.a;
  let atlas_uv = vec2<f32>(
    u0 + uv_local.x * (u1 - u0),
    v0 + uv_local.y * (v1 - v0),
  );
  let sampled = textureSample(sprite_atlas, sprite_samp, atlas_uv);
  // Layer opacity multiplies sprite alpha so fill-opacity still works.
  out.color = vec4<f32>(sampled.rgb, sampled.a * u.opacity);
  out.color.a = out.color.a * polygon_rim_alpha(input.abs_merc_x, input.abs_merc_y);
  
  let base_depth = compute_log_frag_depth(input.view_w, u.log_depth_fc);
  let id_lo = input.feat_id & 0xFFFFu;
  let mixed = (id_lo ^ (id_lo >> 7u) ^ (id_lo << 3u)) & 0x3FFu;
  let jitter = select(
    0.0,
    (f32(mixed) - 512.0) * 1.5e-8,
    input.feat_id != 0u,
  );
  out.depth = base_depth + jitter;
  return out;
}

// Weighted Blended OIT (McGuire-Bavoil 2013) translucent fill output.
// Writes to two MRT slots:
//   @location(0) accum:     vec4<f32> = (rgb·a·w, a·w)   [BLEND_ADD]
//   @location(1) revealage: f32        = a               [BLEND mul-by-1-src]
// The compose pass divides accum.rgb by accum.a to recover the
// weighted-average colour, and uses (1 - product_of_(1-a)) as the
// over-blend alpha onto the opaque framebuffer.
//
// Weight function: McGuire-Bavoil 7.4. The view-w-dependent term
// biases small-z fragments to dominate, matching what painter's
// order would do for clearly-front-most geometry. Clamping prevents
// degenerate cases (very small / very large weights breaking the
// running sums in fp16).
struct OitFragmentOutput {
  @location(0) accum: vec4<f32>,
  @location(1) revealage: f32,
}

@fragment
fn fs_oit_translucent(input: VertexOutput) -> OitFragmentOutput {
  if (polygon_cos_c_fragment(input.abs_merc_x, input.abs_merc_y) < 0.0) { discard; }
  if (abs(input.abs_lat) > MERCATOR_LAT_LIMIT) { discard; }
  // Per-tile clip mask (see fs_fill — robust check requires both
  // sentinel-not-tripped AND the bounds to describe a valid box).
  let _clip_valid =
    u.clip_bounds.x > -1e29 &&
    u.clip_bounds.z > u.clip_bounds.x &&
    u.clip_bounds.w > u.clip_bounds.y;
  if (_clip_valid) {
    if (input.abs_merc_x < u.clip_bounds.x) { discard; }
    if (input.abs_merc_x > u.clip_bounds.z) { discard; }
    if (input.abs_merc_y < u.clip_bounds.y) { discard; }
    if (input.abs_merc_y > u.clip_bounds.w) { discard; }
  }
  // OIT fill-extrusion shading — same as fs_fill (iter 129 final).
  let v_shade = 0.6 + 0.4 * input.wall_blend;
  let roof_bonus = select(0.0, 0.05, input.wall_blend >= 0.999);
  let wall_shade = min(1.0, v_shade + roof_bonus);
  let rgb = u.fill_color.rgb * wall_shade;
  // Rim alpha fade — same as fs_fill. Multiplies into alpha so
  // OIT accumulation respects the soft-rim transition on globe /
  // azimuthal / stereographic / ortho.
  let a = u.fill_color.a * polygon_rim_alpha(input.abs_merc_x, input.abs_merc_y);
  if (a <= 0.001) { discard; }
  // McGuire-Bavoil weight: large for closer (smaller view_w) and
  // smaller alpha contributions, capped to avoid float overflow.
  // (iter-192 set weight=1; reverted in iter-193 alongside the
  // depth-write change — see fillPipelineExtrudedOIT comment.)
  let z = max(input.view_w, 1e-3);
  let w = clamp(0.03 / (1e-5 + pow(z / 200.0, 4.0)), 1e-2, 3.0e3);
  var out: OitFragmentOutput;
  out.accum = vec4<f32>(rgb * a, a) * w;
  out.revealage = a;
  return out;
}

// iter-194 — MapLibre-equivalent fill-extrusion fragment. All
// lighting was computed per-vertex in vs_main_quantized_extruded
// and interpolated as v_color; this fragment just passes it through
// (after the same per-fragment cull + clip discards as fs_fill so
// hemisphere boundaries + parent-tile clip masks stay correct).
// v_color is PREMULTIPLIED (rgb * alpha, alpha); the pipeline uses
// BLEND_ALPHA_PREMULT so the result composites the same way
// MapLibre's translucent extrude path does.
@fragment
fn fs_fill_extrude(input: VertexOutput) -> FragmentOutput {
  if (polygon_cos_c_fragment(input.abs_merc_x, input.abs_merc_y) < 0.0) { discard; }
  if (abs(input.abs_lat) > MERCATOR_LAT_LIMIT) { discard; }
  let _clip_valid =
    u.clip_bounds.x > -1e29 &&
    u.clip_bounds.z > u.clip_bounds.x &&
    u.clip_bounds.w > u.clip_bounds.y;
  if (_clip_valid) {
    if (input.abs_merc_x < u.clip_bounds.x) { discard; }
    if (input.abs_merc_x > u.clip_bounds.z) { discard; }
    if (input.abs_merc_y < u.clip_bounds.y) { discard; }
    if (input.abs_merc_y > u.clip_bounds.w) { discard; }
  }
  var out: FragmentOutput;
  // Rim alpha — operates on the premultiplied colour: scale both
  // rgb and alpha by the rim factor so the building still fades at
  // sphere edges on globe / azimuthal projections.
  let rim = polygon_rim_alpha(input.abs_merc_x, input.abs_merc_y);
  out.color = input.v_color * rim;
  
  let base_depth = compute_log_frag_depth(input.view_w, u.log_depth_fc);
  let id_lo = input.feat_id & 0xFFFFu;
  let mixed = (id_lo ^ (id_lo >> 7u) ^ (id_lo << 3u)) & 0x3FFu;
  let jitter = select(
    0.0,
    (f32(mixed) - 512.0) * 1.5e-8,
    input.feat_id != 0u,
  );
  out.depth = base_depth + jitter;
  return out;
}

@fragment
fn fs_stroke(input: VertexOutput) -> FragmentOutput {
  if (polygon_cos_c_fragment(input.abs_merc_x, input.abs_merc_y) < 0.0) { discard; }
  if (abs(input.abs_lat) > MERCATOR_LAT_LIMIT) { discard; }
  // Per-tile clip mask (see fs_fill — robust check requires both
  // sentinel-not-tripped AND the bounds to describe a valid box).
  let _clip_valid =
    u.clip_bounds.x > -1e29 &&
    u.clip_bounds.z > u.clip_bounds.x &&
    u.clip_bounds.w > u.clip_bounds.y;
  if (_clip_valid) {
    if (input.abs_merc_x < u.clip_bounds.x) { discard; }
    if (input.abs_merc_x > u.clip_bounds.z) { discard; }
    if (input.abs_merc_y < u.clip_bounds.y) { discard; }
    if (input.abs_merc_y > u.clip_bounds.w) { discard; }
  }
  // feat_id > 0 = major grid line (brighter), 0 = minor (dimmer)
  let alpha_scale = select(0.4, 1.0, input.feat_id > 0u);
  var out: FragmentOutput;
  out.color = vec4<f32>(u.stroke_color.rgb, u.stroke_color.a * alpha_scale);
  // Rim alpha fade — same as fs_fill, applied AFTER the marker so
  // variant pipelines inherit it. Smooths stroke fade across the
  // sphere visibility boundary on globe / azimuthal / etc.
  out.color.a = out.color.a * polygon_rim_alpha(input.abs_merc_x, input.abs_merc_y);
  
  out.depth = compute_log_frag_depth(input.view_w, u.log_depth_fc);
  return out;
}

// ?debug=overdraw — single constant-output entry shared by every
// debug-variant pipeline (fill, stroke, fallback, etc.). Vertex
// shaders still project correctly so the rasterizer produces the
// SAME fragments as the normal path; FS work collapses to one
// write that an additive blend sums into the r16float accumulator.
// Counts SUBMITTED overdraw — depth is forced always, no stencil,
// no clip-bounds discard — matching the MapLibre debug convention.
@fragment
fn fs_overdraw() -> @location(0) vec4<f32> {
  return vec4<f32>(1.0, 0.0, 0.0, 0.0);
}

