// ═══ Generate the AWS Open Data half of the bridge's host allowlist ═══
//
// `playground/dev/opendata-bridge.ts` will proxy `/opendata/<host>/<path>` for any host on its
// allowlist. The AWS half of that list is not written by hand — AWS publishes it, in
// `awslabs/open-data-registry`, as one YAML per dataset with an `arn:aws:s3:::<bucket>` and a
// `Region` per S3 resource. This reads that and emits the hosts.
//
// WHY GENERATED. A hand-maintained allowlist is the exact failure this bridge has already paid
// for twice: a hand-maintained prefix LIST in the dev middleware broke on the third product,
// and the `noaa-*` glob that replaced it only worked while the scope was one publisher. A list
// that grows with a registry someone else maintains cannot go stale for the AWS half at all.
//
// WHY THE REGION IS IN THE HOST. `<bucket>.s3.amazonaws.com` answers for any region, but a
// bucket outside us-east-1 answers with a 307 to its regional endpoint — an extra round trip on
// every ranged read, and this bridge exists to serve HDF5 cells over Range. The regional host is
// the address the object actually has.
//
//   node --experimental-strip-types scripts/gen-opendata-hosts.ts
//
// Rerun when a dataset the demos need is missing. The output is committed, so the worker
// resolves its allowlist at module scope with no network and no binding.

import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { execFileSync } from 'node:child_process'
import { mkdtempSync, readdirSync, readFileSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const OUT = join(ROOT, 'playground', 'dev', 'opendata-hosts.generated.ts')
const TARBALL = 'https://codeload.github.com/awslabs/open-data-registry/tar.gz/refs/heads/main'

/** Pull the `Type: S3 Bucket` resources out of one dataset YAML as `[bucket, region]`.
 *
 *  Line-oriented rather than a YAML parse, deliberately: the shape read here is three scalar
 *  keys inside one list of maps under `Resources:`, and every entry in the registry is
 *  machine-generated from the same template. A YAML dependency to read three fields would cost
 *  more than it explains — and unlike a runtime parse, a mistake here is visible in the
 *  committed diff before it can reach anything. */
function s3ResourcesOf(yaml: string): Array<[string, string]> {
  const out: Array<[string, string]> = []
  let inResources = false
  let arn: string | null = null
  let region: string | null = null
  let type: string | null = null

  const flush = (): void => {
    if (type === 'S3 Bucket' && arn) {
      const m = /^arn:aws:s3:::([a-z0-9][a-z0-9.-]{1,61}[a-z0-9])(?:\/|$)/.exec(arn)
      if (m) out.push([m[1]!, region ?? 'us-east-1'])
    }
    arn = region = type = null
  }

  for (const line of yaml.split('\n')) {
    if (/^[A-Za-z]/.test(line)) {
      // A new top-level key ends the Resources block (and the item it was collecting).
      if (inResources) flush()
      inResources = line.startsWith('Resources:')
      continue
    }
    if (!inResources) continue
    if (/^\s{2}-\s/.test(line)) flush() // a new list item starts; commit the previous one
    const kv = /^\s+-?\s*(ARN|Region|Type):\s*"?([^"\n]*?)"?\s*$/.exec(line)
    if (!kv) continue
    if (kv[1] === 'ARN') arn = kv[2]!
    else if (kv[1] === 'Region') region = kv[2]!
    else type = kv[2]!
  }
  if (inResources) flush()
  return out
}

/** `<bucket>.s3.<region>.amazonaws.com` — the address the object actually has. */
const hostOf = (bucket: string, region: string): string => `${bucket}.s3.${region}.amazonaws.com`

const work = mkdtempSync(join(tmpdir(), 'odr-'))
try {
  const res = await fetch(TARBALL)
  if (!res.ok) throw new Error(`open-data-registry tarball: HTTP ${res.status}`)
  const tar = join(work, 'registry.tar.gz')
  writeFileSync(tar, Buffer.from(await res.arrayBuffer()))
  execFileSync('tar', ['xzf', tar, '-C', work], { stdio: 'inherit' })

  const root = readdirSync(work).find((d) => d.startsWith('open-data-registry-'))
  if (!root) throw new Error('extracted tarball has no open-data-registry-* directory')
  const datasets = join(work, root, 'datasets')

  const hosts = new Map<string, string>() // host → the dataset file that introduced it
  let files = 0
  for (const name of readdirSync(datasets)) {
    if (!name.endsWith('.yaml')) continue
    files++
    for (const [bucket, region] of s3ResourcesOf(readFileSync(join(datasets, name), 'utf8'))) {
      const host = hostOf(bucket, region)
      if (!hosts.has(host)) hosts.set(host, name.replace(/\.yaml$/, ''))
    }
  }
  if (files === 0) throw new Error('no dataset YAML found — has the registry layout moved?')

  const sorted = [...hosts.keys()].sort()
  writeFileSync(
    OUT,
    `// GENERATED by scripts/gen-opendata-hosts.ts — DO NOT EDIT.\n` +
      `//\n` +
      `// The AWS Open Data half of the bridge's host allowlist, from awslabs/open-data-registry\n` +
      `// (${files} datasets → ${sorted.length} S3 hosts). Hand-added, non-AWS open-data hosts go in\n` +
      `// opendata-hosts.ts instead — this file is overwritten wholesale on every regeneration.\n` +
      `\n` +
      `export const AWS_OPEN_DATA_HOSTS: readonly string[] = [\n` +
      sorted.map((h) => `  '${h}',\n`).join('') +
      `]\n`,
  )
  console.log(`${files} datasets → ${sorted.length} hosts → ${OUT}`)
} finally {
  rmSync(work, { recursive: true, force: true })
}
