import type { RuntimeCapability } from './types'

// `symbol` layer capability rows — text + icon paint/layout (rendered by
// the TextStage / IconStage / label pipeline). Only place a symbol-axis
// change touches the capability table.
export const symbolCapabilities: readonly RuntimeCapability[] = [
  // Text paint
  { property: 'text-color', layerType: 'symbol', variant: 'constant', supported: true },
  { property: 'text-color', layerType: 'symbol', variant: 'zoom-interp', supported: true },
  { property: 'text-color', layerType: 'symbol', variant: 'data-driven', supported: true },
  { property: 'text-opacity', layerType: 'symbol', variant: 'constant', supported: true },
  {
    property: 'text-opacity',
    layerType: 'symbol',
    variant: 'zoom-interp',
    supported: true,
    note: 'WS-1 — LabelShapes.opacity PropertyShape resolved per frame in render-loop-helpers (resolveNumberShape into resolvedColor.a + halo.a). Iter 113.',
  },
  {
    property: 'text-opacity',
    layerType: 'symbol',
    variant: 'data-driven',
    supported: false,
    note: 'Per-feature alpha path deferred',
  },
  { property: 'text-halo-color', layerType: 'symbol', variant: 'constant', supported: true },
  { property: 'text-halo-color', layerType: 'symbol', variant: 'zoom-interp', supported: true },
  { property: 'text-halo-width', layerType: 'symbol', variant: 'constant', supported: true },
  { property: 'text-halo-width', layerType: 'symbol', variant: 'zoom-interp', supported: true },
  {
    property: 'text-pitch-alignment',
    layerType: 'symbol',
    variant: 'constant',
    supported: false,
    note: 'Runtime never projects labels onto ground plane',
  },

  // Icon paint
  {
    property: 'icon-color',
    layerType: 'symbol',
    variant: 'constant',
    supported: true,
    note: 'SDF sprite tint — label-icon-color-<hex> → lower-label → IconStage per-vertex tint, sampled by the SDF branch of the icon FS (icon.ts:64-67). Raster sprites ignore it.',
  },
  {
    property: 'icon-color',
    layerType: 'symbol',
    variant: 'zoom-interp',
    supported: true,
    note: 'label-icon-color-[interp] PropertyShape resolved per frame (lower-label iter 138).',
  },
  {
    property: 'icon-color',
    layerType: 'symbol',
    variant: 'data-driven',
    supported: true,
    note: 'match/case → label-icon-color-[<expr>] per-feature binding (lower-label iter 138).',
  },
  { property: 'icon-opacity', layerType: 'symbol', variant: 'constant', supported: true },
  {
    property: 'icon-opacity',
    layerType: 'symbol',
    variant: 'zoom-interp',
    supported: true,
    note: 'label-icon-opacity-[interp] → LabelShapes.iconOpacity zoom-interpolated PropertyShape resolved per frame by resolveLabelEffectiveDef (render-loop-helpers → resolveNumberShape → effectiveDef.iconOpacity → IconStage.addIcon per-vertex alpha). #777 I-F: row was stale (path already existed via iter 113); wiring-test render-loop-helpers-icon-opacity-zoom.test.ts flipped it.',
  },
  {
    property: 'icon-opacity',
    layerType: 'symbol',
    variant: 'data-driven',
    supported: true,
    note: 'match/case/get → label-icon-opacity-[<expr>] → LabelShapes.iconOpacity data-driven; runtime applyFeatureExprs (label-pass.ts) evaluates the AST per feature → effectiveDef.iconOpacity → IconStage.addIcon per-vertex alpha. #777 I-F.',
  },
  { property: 'icon-size', layerType: 'symbol', variant: 'constant', supported: true },
  { property: 'icon-size', layerType: 'symbol', variant: 'zoom-interp', supported: true },
  {
    property: 'icon-size',
    layerType: 'symbol',
    variant: 'data-driven',
    supported: true,
    note: 'match/case/get → label-icon-size-[<expr>] (converter exprToXgis) → LabelShapes.iconSize data-driven; runtime applyFeatureExprs (label-pass.ts) evaluates the AST per feature (clamped >= 0) → effectiveDef.iconSize → IconStage sizeScale → per-vertex quad width. #777 I-F.',
  },
  { property: 'symbol-sort-key', layerType: 'symbol', variant: 'constant', supported: true },
  {
    property: 'symbol-sort-key',
    layerType: 'symbol',
    variant: 'data-driven',
    supported: false,
    note: 'Expression flattens to 0; per-feature key plumbing pending',
  },

  // Symbol layout — common
  {
    property: 'symbol-placement',
    layerType: 'symbol',
    variant: 'constant',
    supported: true,
    note: 'point / line / line-center literal',
  },
  { property: 'symbol-spacing', layerType: 'symbol', variant: 'constant', supported: true },

  // Symbol text layout
  { property: 'text-field', layerType: 'symbol', variant: 'constant', supported: true },
  { property: 'text-field', layerType: 'symbol', variant: 'data-driven', supported: true },
  { property: 'text-font', layerType: 'symbol', variant: 'constant', supported: true },
  { property: 'text-size', layerType: 'symbol', variant: 'constant', supported: true },
  { property: 'text-size', layerType: 'symbol', variant: 'zoom-interp', supported: true },
  {
    property: 'text-size',
    layerType: 'symbol',
    variant: 'data-driven',
    supported: true,
    note: 'sizeExpr per-feature evaluation',
  },
  { property: 'text-max-width', layerType: 'symbol', variant: 'constant', supported: true },
  { property: 'text-line-height', layerType: 'symbol', variant: 'constant', supported: true },
  { property: 'text-letter-spacing', layerType: 'symbol', variant: 'constant', supported: true },
  { property: 'text-letter-spacing', layerType: 'symbol', variant: 'zoom-interp', supported: true },
  {
    property: 'text-justify',
    layerType: 'symbol',
    variant: 'constant',
    supported: true,
    note: 'auto / left / center / right literal',
  },
  {
    property: 'text-anchor',
    layerType: 'symbol',
    variant: 'constant',
    supported: true,
    note: '9-way enum literal',
  },
  { property: 'text-variable-anchor', layerType: 'symbol', variant: 'constant', supported: true },
  {
    property: 'text-variable-anchor-offset',
    layerType: 'symbol',
    variant: 'constant',
    supported: true,
  },
  { property: 'text-radial-offset', layerType: 'symbol', variant: 'constant', supported: true },
  { property: 'text-offset', layerType: 'symbol', variant: 'constant', supported: true },
  { property: 'text-rotate', layerType: 'symbol', variant: 'constant', supported: true },
  { property: 'text-padding', layerType: 'symbol', variant: 'constant', supported: true },
  { property: 'text-padding', layerType: 'symbol', variant: 'zoom-interp', supported: true },
  {
    property: 'text-transform',
    layerType: 'symbol',
    variant: 'constant',
    supported: true,
    note: 'uppercase / lowercase / none literal',
  },
  { property: 'text-allow-overlap', layerType: 'symbol', variant: 'constant', supported: true },
  { property: 'text-ignore-placement', layerType: 'symbol', variant: 'constant', supported: true },
  {
    property: 'text-rotation-alignment',
    layerType: 'symbol',
    variant: 'constant',
    supported: true,
    note: 'map / viewport / auto literal',
  },
  { property: 'text-keep-upright', layerType: 'symbol', variant: 'constant', supported: true },
  {
    property: 'text-max-angle',
    layerType: 'symbol',
    variant: 'constant',
    supported: true,
    note: 'LabelDef.maxAngle drives the TextStage curved-label angular gate; unset = no clamp (historical behaviour)',
  },
  {
    property: 'symbol-z-order',
    layerType: 'symbol',
    variant: 'constant',
    supported: true,
    note: 'auto / viewport-y / source enum → LabelDef.symbolZOrder → TextStage.prepare() ordering pass. viewport-y orders by screen Y (south drawn on top); source keeps feature order; auto/unset = legacy reverse-layer / sortKey ordering (byte-identical default)',
  },
  { property: 'text-translate', layerType: 'symbol', variant: 'constant', supported: true },
  {
    property: 'text-translate-anchor',
    layerType: 'symbol',
    variant: 'constant',
    supported: true,
    note: 'viewport (default) = screen-space (byte-identical); map = world-space: TextStage.prepare rotates the [dx,dy] text-translate by camera.bearing (rotateLabelTranslate, mirror of the fill/line clip-space bake) and re-keys the layout cache. Pitch foreshortening not reproduced.',
  },
  {
    property: 'text-halo-blur',
    layerType: 'symbol',
    variant: 'constant',
    supported: true,
    note: 'IR exposes PropertyShape; non-constant emits warn until shape-resolve lands',
  },

  // Symbol icon layout
  { property: 'icon-image', layerType: 'symbol', variant: 'constant', supported: true },
  {
    property: 'icon-image',
    layerType: 'symbol',
    variant: 'data-driven',
    supported: true,
    note: 'match/case via label-icon-image-[<expr>] (iter 490)',
  },
  { property: 'icon-rotate', layerType: 'symbol', variant: 'constant', supported: true },
  {
    property: 'icon-anchor',
    layerType: 'symbol',
    variant: 'constant',
    supported: true,
    note: '9-way enum literal',
  },
  { property: 'icon-offset', layerType: 'symbol', variant: 'constant', supported: true },
  {
    property: 'icon-rotation-alignment',
    layerType: 'symbol',
    variant: 'constant',
    supported: true,
    note: 'map / viewport / auto literal (iter 506)',
  },
  {
    property: 'icon-translate-anchor',
    layerType: 'symbol',
    variant: 'constant',
    supported: true,
    note: 'viewport (default) = screen-space (byte-identical); map = world-space: dispatchIcon rotates ONLY the icon-translate portion of the icon anchor offset by camera.bearing (icon-offset stays screen-space). Pitch foreshortening not reproduced.',
  },
  {
    property: 'icon-allow-overlap',
    layerType: 'symbol',
    variant: 'constant',
    supported: true,
    note: 'false → LabelDef.iconCollide → IconStage collide AABB (#417/#419); absent/true = always-place (Phase S Batch 4)',
  },
  {
    property: 'icon-overlap',
    layerType: 'symbol',
    variant: 'constant',
    supported: true,
    note: 'never → collide; cooperative ≈ never + warn; always = always-place (Phase S Batch 4)',
  },
  {
    property: 'icon-ignore-placement',
    layerType: 'symbol',
    variant: 'constant',
    supported: true,
    note: "true → LabelDef.iconIgnorePlacement: place + don't block (overrides iconCollide) (Phase S Batch 4)",
  },
  {
    property: 'icon-optional',
    layerType: 'symbol',
    variant: 'constant',
    supported: true,
    note: 'true → LabelDef.iconOptional: colliding icon may hide while paired text shows; default false reverse-arbitration deferred (Phase S Batch 4)',
  },
]
